import { getSupabaseClient } from '@/lib/supabase';

export type BusinessWorkspace={id:string;business_id:string;user_id:string;role:string;created_at:string;business_name:string|null;name:string|null;business_tier:string|null;is_demo_test:boolean};
export type BusinessProductAccess={business_id:string;plan:string;location_count:number;location_limit:number|null;enterprise_enabled:boolean;fleet_enabled:boolean;is_admin:boolean};
export type BusinessLocation={id:string;business_id?:string|null;name:string;address?:string|null;city?:string|null;state?:string|null;postal_code?:string|null;latitude?:number|null;longitude?:number|null;phone?:string|null;website?:string|null;is_active?:boolean|null;active?:boolean|null;[key:string]:unknown};
export type BusinessAmenity={amenity_id:string;name:string;category:string|null};
export type BusinessMedia={id:string;location_id:string|null;location_name:string|null;storage_path:string;caption:string|null;media_type:string|null;mime_type:string|null;size_bytes:number|null;width:number|null;height:number|null;sort_order:number|null;created_at:string};
export type BusinessProfileUpdate={name:string;description?:string|null;website?:string|null;phone?:string|null;email?:string|null;logo_url?:string|null};
export type LocationInput={name:string;address?:string|null;city?:string|null;state?:string|null;postalCode?:string|null;latitude?:number|null;longitude?:number|null;phone?:string|null;website?:string|null};
const client=()=>getSupabaseClient();
function unwrap<T>(data:T|null,error:{message:string}|null):T{if(error)throw new Error(error.message);if(data==null)throw new Error('Canonical Business service returned no data.');return data;}
export async function getCurrentSession(){const{data,error}=await client().auth.getSession();if(error)throw error;return data.session;}
export async function listBusinessWorkspaces(includeDemo=false):Promise<BusinessWorkspace[]>{const{data,error}=await client().rpc('business_list_workspaces',{p_include_demo:includeDemo});return unwrap((data??[]) as BusinessWorkspace[],error);}
export async function getBusinessProductAccess(businessId:string):Promise<BusinessProductAccess>{const{data,error}=await client().rpc('get_business_product_access',{p_business_id:businessId});const rows=unwrap((data??[]) as BusinessProductAccess[],error);if(!rows[0])throw new Error('No Business product access is available for this workspace.');return rows[0];}
export async function getBusinessServiceEntitlement(businessId:string){const{data,error}=await client().rpc('get_business_service_entitlement',{p_business_id:businessId});return unwrap(data as Record<string,unknown>|null,error);}
export async function getBusinessManagementContext(businessId:string){const{data,error}=await client().rpc('business_management_context',{p_business_id:businessId});return unwrap(data as Record<string,unknown>|null,error);}
export async function getBusinessProfile(businessId:string){const{data,error}=await client().rpc('business_get_profile',{p_business_id:businessId});return unwrap(data as Record<string,unknown>|null,error);}
export async function updateBusinessProfile(businessId:string,input:BusinessProfileUpdate){const{data,error}=await client().rpc('business_update_profile',{p_business_id:businessId,p_name:input.name,p_description:input.description??null,p_website:input.website??null,p_phone:input.phone??null,p_email:input.email??null,p_logo_url:input.logo_url??null});return unwrap(data,error);}
export async function listBusinessLocations(businessId:string):Promise<BusinessLocation[]>{const{data,error}=await client().rpc('business_list_locations',{p_business_id:businessId});return unwrap((data??[]) as BusinessLocation[],error);}
export async function createBusinessLocation(businessId:string,input:LocationInput){const{data,error}=await client().rpc('business_create_location_canonical',{p_business_id:businessId,p_name:input.name,p_address:input.address??null,p_city:input.city??null,p_state:input.state??null,p_postal_code:input.postalCode??null,p_latitude:input.latitude??null,p_longitude:input.longitude??null,p_phone:input.phone??null,p_website:input.website??null});return unwrap(data as BusinessLocation|null,error);}
export async function updateBusinessLocation(locationId:string,input:Pick<LocationInput,'name'|'address'|'phone'|'website'>&{active:boolean}){const{data,error}=await client().rpc('business_update_location_canonical',{p_location_id:locationId,p_name:input.name,p_address:input.address??null,p_phone:input.phone??null,p_website:input.website??null,p_active:input.active});return unwrap(data as BusinessLocation|null,error);}
export async function setBusinessLocationActive(locationId:string,active:boolean){const{data,error}=await client().rpc('business_set_location_active_canonical',{p_location_id:locationId,p_active:active});return unwrap(Boolean(data),error);}
export async function manageBusinessLocation(businessId:string,locationId:string|null,action:string,payload:Record<string,unknown>){const{data,error}=await client().rpc('business_manage_location',{p_business_id:businessId,p_location_id:locationId,p_action:action,p_payload:payload});return unwrap(data,error);}
export async function listLocationAmenities(businessId:string,locationId:string):Promise<BusinessAmenity[]>{const{data,error}=await client().rpc('business_list_amenities',{p_business_id:businessId,p_location_id:locationId});return unwrap((data??[]) as BusinessAmenity[],error);}
export async function getLocationAmenityInventory(locationId:string){const{data,error}=await client().rpc('get_location_amenity_inventory',{p_location_id:locationId});return unwrap(data as Record<string,unknown>|unknown[]|null,error);}
export async function replaceLocationAmenities(locationId:string,amenityIds:string[]){const{data,error}=await client().rpc('set_location_amenities',{p_location_id:locationId,p_amenity_ids:amenityIds});return unwrap(data as Record<string,unknown>|null,error);}
export async function setLocationAmenity(businessId:string,locationId:string,amenityId:string,action:'add'|'remove'){const{data,error}=await client().rpc('business_set_location_amenity',{p_business_id:businessId,p_location_id:locationId,p_amenity_id:amenityId,p_action:action});return unwrap(data,error);}
export async function listBusinessMedia(businessId:string):Promise<BusinessMedia[]>{const{data,error}=await client().rpc('business_list_media',{p_business_id:businessId});return unwrap((data??[]) as BusinessMedia[],error);}
export async function createBusinessMedia(businessId:string,input:{locationId:string;storagePath:string;caption?:string|null;mediaType?:string|null;mimeType?:string|null;sizeBytes?:number|null;width?:number|null;height?:number|null;sortOrder?:number|null}){const{data,error}=await client().rpc('business_create_media',{p_business_id:businessId,p_location_id:input.locationId,p_storage_path:input.storagePath,p_caption:input.caption??null,p_media_type:input.mediaType??null,p_mime_type:input.mimeType??null,p_size_bytes:input.sizeBytes??null,p_width:input.width??null,p_height:input.height??null,p_sort_order:input.sortOrder??null});return unwrap(data as string|null,error);}
export async function updateBusinessMedia(businessId:string,mediaId:string,input:{storagePath?:string|null;caption?:string|null;mediaType?:string|null;sortOrder?:number|null}){const{data,error}=await client().rpc('business_update_media',{p_business_id:businessId,p_media_id:mediaId,p_storage_path:input.storagePath??null,p_caption:input.caption??null,p_media_type:input.mediaType??null,p_sort_order:input.sortOrder??null});return unwrap(data as string|null,error);}
export async function deleteBusinessMedia(businessId:string,mediaId:string){const{data,error}=await client().rpc('business_delete_media',{p_business_id:businessId,p_media_id:mediaId});return unwrap(Boolean(data),error);}
export async function inviteBusinessMember(businessId:string,userId:string,role:string){const{data,error}=await client().rpc('business_invite_member',{p_business_id:businessId,p_user_id:userId,p_role:role});return unwrap(data,error);}
export async function changeBusinessMemberRole(businessId:string,userId:string,role:string){const{data,error}=await client().rpc('business_change_member_role',{p_business_id:businessId,p_user_id:userId,p_role:role});return unwrap(data,error);}
export async function removeBusinessMember(businessId:string,userId:string){const{data,error}=await client().rpc('business_remove_member',{p_business_id:businessId,p_user_id:userId});return unwrap(Boolean(data),error);}
export async function transferBusinessOwnership(businessId:string,newOwnerId:string){const{data,error}=await client().rpc('business_transfer_ownership',{p_business_id:businessId,p_new_owner_id:newOwnerId});return unwrap(data,error);}
export async function getBusinessReviewDetail(businessId:string,days=30){const end=new Date(),start=new Date(end.getTime()-days*86400000);const{data,error}=await client().rpc('business_review_detail',{p_business_id:businessId,p_start:start.toISOString(),p_end:end.toISOString()});return unwrap(data as Record<string,unknown>|unknown[]|null,error);}
export async function replyToBusinessReview(businessId:string,reviewId:string,reply:string){const{data,error}=await client().rpc('business_reply_review',{p_business_id:businessId,p_review_id:reviewId,p_reply:reply});return unwrap(data as Record<string,unknown>|null,error);}
export async function getBusinessDashboardSummary(businessId:string,days=30){const end=new Date(),start=new Date(end.getTime()-days*86400000);const{data,error}=await client().rpc('business_dashboard_secure_summary',{p_business_id:businessId,p_start:start.toISOString(),p_end:end.toISOString()});return unwrap(data as Record<string,unknown>|null,error);}
