import { getSupabaseClient } from '@/lib/supabase';
const client=()=>getSupabaseClient();
function unwrap<T>(data:T|null,error:{message:string}|null):T{if(error)throw new Error(error.message);if(data==null)throw new Error('Trust operations returned no data.');return data;}
export async function getRemediationOperations(businessId:string){const{data,error}=await client().rpc('business_restroom_remediation_operations',{p_business_id:businessId});return unwrap(data as Record<string,unknown>|null,error);}
export async function manageRemediation(businessId:string,caseId:string,action:'assign'|'claim'|'start'|'release'|'dismiss'|'reopen'|'resolve',options:{assignedTo?:string|null;notes?:string|null;proofMediaId?:string|null}={}){const{data,error}=await client().rpc('business_manage_restroom_remediation',{p_business_id:businessId,p_case_id:caseId,p_action:action,p_assigned_to:options.assignedTo??null,p_notes:options.notes??null,p_proof_media_id:options.proofMediaId??null});return unwrap(data as Record<string,unknown>|null,error);}
export async function getRemediationPerformance(businessId:string,days=90){const{data,error}=await client().rpc('business_restroom_remediation_performance',{p_business_id:businessId,p_days:days});return unwrap(data as Record<string,unknown>|null,error);}
export async function getReverificationOperations(businessId:string){const{data,error}=await client().rpc('business_reverification_operations',{p_business_id:businessId});return unwrap(data as Record<string,unknown>|null,error);}
export async function manageReverification(businessId:string,caseId:string,action:'assign_to_me'|'release'|'dismiss'|'reopen'){const{data,error}=await client().rpc('business_manage_reverification_case',{p_business_id:businessId,p_case_id:caseId,p_action:action});return unwrap(data as Record<string,unknown>|null,error);}
export async function createReverificationQr(businessId:string,locationId:string){const{data,error}=await client().rpc('business_create_reverification_qr',{p_business_id:businessId,p_location_id:locationId});return unwrap(data as Record<string,unknown>|null,error);}
