import { useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { useBusinessWorkspace } from '@/state/businessWorkspace';
import { getBusinessSponsorshipSnapshot,saveBusinessSponsoredCampaign,withdrawBusinessSponsoredCampaign,type BusinessSponsoredCampaign,type SponsoredPlacement } from '@/services/advertising';

const csv=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
const human=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function Advertising(){
 const{workspace}=useBusinessWorkspace();
 const[placements,setPlacements]=useState<SponsoredPlacement[]>([]),[campaigns,setCampaigns]=useState<BusinessSponsoredCampaign[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const[editingId,setEditingId]=useState<string|null>(null),[name,setName]=useState(''),[headline,setHeadline]=useState(''),[body,setBody]=useState(''),[cta,setCta]=useState('Learn more'),[url,setUrl]=useState('');
 const[region,setRegion]=useState(''),[route,setRoute]=useState(''),[amenities,setAmenities]=useState(''),[timeBucket,setTimeBucket]=useState(''),[interests,setInterests]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const businessId=workspace?.business_id||'';

 async function load(){if(!businessId)return;setBusy(true);try{const data:any=await getBusinessSponsorshipSnapshot(businessId);setPlacements(data.placements);setCampaigns(data.campaigns);setMessage('')}catch(e:any){setMessage(e?.message||'Advertising workspace unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[businessId]);
 function reset(){setEditingId(null);setName('');setHeadline('');setBody('');setCta('Learn more');setUrl('');setRegion('');setRoute('');setAmenities('');setTimeBucket('');setInterests('');setSelected([])}
 function edit(row:BusinessSponsoredCampaign){setEditingId(row.id);setName(row.name||'');setHeadline(row.headline||'');setBody(row.body||'');setCta(row.cta_label||'Learn more');setUrl(row.destination_url||'');const t=row.targeting||{};setRegion(String(t.coarse_region||''));setRoute(String(t.route_context||''));setAmenities(Array.isArray(t.amenities)?t.amenities.join(', '):'');setTimeBucket(String(t.time_bucket||''));setInterests(Array.isArray(t.broad_interests)?t.broad_interests.join(', '):'');setSelected(Array.isArray(row.placements)?row.placements:[])}
 function toggle(code:string){setSelected(cur=>cur.includes(code)?cur.filter(x=>x!==code):[...cur,code])}
 const targeting=useMemo(()=>{const t:Record<string,unknown>={};if(region.trim())t.coarse_region=region.trim();if(route.trim())t.route_context=route.trim();if(csv(amenities).length)t.amenities=csv(amenities);if(timeBucket.trim())t.time_bucket=timeBucket.trim();if(csv(interests).length)t.broad_interests=csv(interests);return t},[region,route,amenities,timeBucket,interests]);
 async function save(submit:boolean){if(!businessId||!name.trim()||!headline.trim()||!url.trim()||!selected.length){setMessage('Campaign name, headline, destination URL and at least one placement are required.');return}setBusy(true);try{await saveBusinessSponsoredCampaign(businessId,{id:editingId,name:name.trim(),headline:headline.trim(),body:body.trim(),ctaLabel:cta.trim()||'Learn more',destinationUrl:url.trim(),targeting,placementCodes:selected,submit});setMessage(submit?'Campaign submitted to Kleenest for activation.':'Campaign draft saved.');reset();await load()}catch(e:any){setMessage(e?.message||'Campaign could not be saved.')}finally{setBusy(false)}}
 async function withdraw(id:string){setBusy(true);try{await withdrawBusinessSponsoredCampaign(businessId,id);setMessage('Campaign withdrawn.');await load()}catch(e:any){setMessage(e?.message||'Campaign could not be withdrawn.')}finally{setBusy(false)}}
 if(!workspace)return <View style={{padding:20}}><Text>Business workspace required.</Text></View>;
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:72}}>
  <View style={hero}><Text style={eyebrow}>KLEENEST BUSINESS · ADVERTISE</Text><Text style={heroTitle}>Reach people when your business is actually useful.</Text><Text style={heroBody}>Contextual sponsored recommendations fit into Kleenest workflows without changing trust, freshness, verification or organic ranking.</Text></View>
  {message?<View style={notice}><Text style={{fontWeight:'800'}}>{message}</Text></View>:null}
  <View style={card}><Text style={heading}>{editingId?'Edit sponsored campaign':'Create sponsored campaign'}</Text><Text style={muted}>Remove Ads only removes AdMob/network ads. Direct Kleenest Sponsored recommendations remain part of the discovery experience.</Text>
   <Field label="Campaign name" value={name} set={setName} placeholder="Weekend family traveler offer"/><Field label="Headline" value={headline} set={setHeadline} placeholder="A clean family restroom is nearby"/><Field label="Body" value={body} set={setBody} placeholder="Useful context or offer"/><Field label="CTA" value={cta} set={setCta} placeholder="View location"/><Field label="Destination URL" value={url} set={setUrl} placeholder="https://…"/>
   <Text style={kicker}>CONTEXTUAL TARGETING</Text><Field label="Area / coarse region" value={region} set={setRegion} placeholder="St. Louis metro"/><Field label="Route context" value={route} set={setRoute} placeholder="nearby, road trip, commuter"/><Field label="Amenities" value={amenities} set={setAmenities} placeholder="changing table, accessible"/><Field label="Time context" value={timeBucket} set={setTimeBucket} placeholder="morning, lunch, evening"/><Field label="Broad interests" value={interests} set={setInterests} placeholder="family travel, road trips"/>
   <Text style={kicker}>PLACEMENTS</Text><View style={row}>{placements.map(p=>{const on=selected.includes(p.placement_code);return <Pressable key={p.placement_code} onPress={()=>toggle(p.placement_code)} style={[chip,on&&chipActive]}><Text style={[chipText,on&&chipTextActive]}>{human(p.placement_code)}</Text></Pressable>})}</View>
   <Text style={kicker}>CONSUMER PREVIEW</Text><View style={preview}><Text style={sponsored}>SPONSORED · {String(workspace.business_name||workspace.name||'YOUR BUSINESS').toUpperCase()}</Text><Text style={previewTitle}>{headline.trim()||'Your useful headline appears here'}</Text><Text style={muted}>{body.trim()||'Keep it useful and contextual so it feels like part of the Kleenest workflow.'}</Text><View style={previewCta}><Text style={{fontWeight:'900',color:'#173f2d'}}>{cta.trim()||'Learn more'} →</Text></View><Text style={disclosure}>Paid placement. Sponsorship does not change Kleenest trust, freshness, verification or ranking.</Text></View>
   <View style={row}><Action label="Save draft" onPress={()=>save(false)}/><Action label="Submit for activation" onPress={()=>save(true)}/>{editingId?<Action label="Cancel edit" onPress={reset}/>:null}</View>
  </View>
  <View style={{gap:10}}><Text style={heading}>Your sponsored campaigns</Text>{campaigns.length?campaigns.map(r=><View key={r.id} style={card}><Text style={{fontWeight:'900',fontSize:16}}>{r.headline}</Text><Text style={muted}>{human(r.submission_status||r.status)} · {r.impressions||0} impressions · {r.clicks||0} clicks</Text>{r.review_note?<Text style={muted}>Kleenest note: {r.review_note}</Text>:null}<View style={row}>{r.status!=='active'&&r.submission_status!=='submitted'?<Action label="Edit" onPress={()=>edit(r)}/>:null}{r.submission_status!=='withdrawn'?<Action label="Withdraw" onPress={()=>withdraw(r.id)}/>:null}</View></View>):<Text style={muted}>No sponsored campaigns yet.</Text>}</View>
 </ScrollView>;
}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <View style={{gap:4}}><Text style={muted}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} style={input}/></View>}
function Action({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={action}><Text style={{fontWeight:'900',color:'white'}}>{label}</Text></Pressable>}
const hero={backgroundColor:'#173f2d' as const,borderRadius:22,padding:18,gap:7},eyebrow={fontSize:10,fontWeight:'900' as const,letterSpacing:1.1,color:'#bfe0cd' as const},heroTitle={fontSize:25,fontWeight:'900' as const,color:'white' as const},heroBody={color:'#dce9e2' as const,lineHeight:20},notice={backgroundColor:'#fff8e8' as const,borderRadius:14,padding:12},card={backgroundColor:'white' as const,borderRadius:18,padding:15,gap:10},heading={fontSize:20,fontWeight:'900' as const,color:'#173024' as const},muted={color:'#66766e' as const,lineHeight:19},kicker={fontSize:10,fontWeight:'900' as const,letterSpacing:1.1,color:'#547060' as const},input={borderWidth:1,borderColor:'#d6e1da',borderRadius:12,paddingHorizontal:12,paddingVertical:11,backgroundColor:'#fafcfb' as const},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},chip={borderWidth:1,borderColor:'#d6e1da' as const,borderRadius:999,paddingHorizontal:10,paddingVertical:8,backgroundColor:'#f4f8f5' as const},chipActive={backgroundColor:'#173f2d' as const},chipText={fontWeight:'900' as const,fontSize:11,color:'#173f2d' as const},chipTextActive={color:'white' as const},preview={borderWidth:1,borderColor:'#d6e1da' as const,borderRadius:17,padding:13,gap:6,backgroundColor:'#f7faf8' as const},sponsored={fontSize:9,fontWeight:'900' as const,letterSpacing:1.1,color:'#65756b' as const},previewTitle={fontSize:17,fontWeight:'900' as const,color:'#173024' as const},previewCta={alignSelf:'flex-start' as const,borderWidth:1,borderColor:'#d6e1da' as const,borderRadius:11,paddingHorizontal:10,paddingVertical:8},disclosure={fontSize:9,lineHeight:13,fontWeight:'700' as const,color:'#65756b' as const},action={backgroundColor:'#173f2d' as const,borderRadius:999,paddingHorizontal:12,paddingVertical:10};
