import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { createQrEngagementProgram,getCoreEngagementBundle,getEngagementBundle,listCampaigns,listContests,listEvents,listQrEngagementPrograms,manageCampaign,manageContest,manageEvent,managePromotion,manageQr,setPromotionActive,setQrActive,setQrCustomization,type EngagementRecord } from '@/services/engagement';
import { listBusinessLocations } from '@/services/business';
import { getBusinessTierCapabilities } from '@/domain/businessTiers';
import { useBusinessWorkspace } from '@/state/businessWorkspace';

type Bundle=Awaited<ReturnType<typeof getCoreEngagementBundle>>|Awaited<ReturnType<typeof getEngagementBundle>>;
type Draft={name:string;description:string;goal:string;discount:string;date:string;time:string};
const blank:Draft={name:'',description:'',goal:'',discount:'',date:'',time:''};
function arrayFrom(value:unknown):EngagementRecord[]{if(Array.isArray(value))return value.filter((x):x is EngagementRecord=>Boolean(x&&typeof x==='object'));if(value&&typeof value==='object')for(const key of['items','rows','campaigns','events','promotions','qr_codes','qrs','detail']){const nested=(value as Record<string,unknown>)[key];if(Array.isArray(nested))return nested.filter((x):x is EngagementRecord=>Boolean(x&&typeof x==='object'));}return[];}
function titleOf(x:EngagementRecord,f:string){return String(x.title??x.name??x.label??f);}
function idOf(x:EngagementRecord){return String(x.id??'');}

export default function BusinessEngagementScreen(){
 const{workspace,access,entitlement,refresh:rw}=useBusinessWorkspace();
 const caps=getBusinessTierCapabilities(access,entitlement);
 const advanced=caps.advancedEngagement;
 const[campaigns,setCampaigns]=useState<EngagementRecord[]>([]),[contests,setContests]=useState<EngagementRecord[]>([]),[events,setEvents]=useState<EngagementRecord[]>([]),[bundle,setBundle]=useState<Bundle|null>(null),[locationId,setLocationId]=useState<string|null>(null),[programCounts,setProgramCounts]=useState<Record<string,number>>({}),[draft,setDraft]=useState<Draft>(blank),[editing,setEditing]=useState<{kind:'campaign'|'contest'|'event'|'promotion';item:EngagementRecord}|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!workspace)return;const id=workspace.business_id;const l=await listBusinessLocations(id);setLocationId(l[0]?.id??null);if(advanced){const[c,co,e,b]=await Promise.all([listCampaigns(id),listContests(id),listEvents(id),getEngagementBundle(id)]);setCampaigns(c);setContests(co);setEvents(e);setBundle(b);}else{setCampaigns([]);setContests([]);setEvents([]);setBundle(await getCoreEngagementBundle(id));}const q=arrayFrom((advanced?await getEngagementBundle(id):await getCoreEngagementBundle(id)).qr);setProgramCounts(Object.fromEntries(await Promise.all(q.filter(x=>x.id).map(async x=>[idOf(x),(await listQrEngagementPrograms(idOf(x))).length] as const))));},[workspace,advanced]);
 useEffect(()=>{setLoading(true);load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false));},[load]);
 const promotions=useMemo(()=>arrayFrom(bundle?.promotions),[bundle]),qrs=useMemo(()=>arrayFrom(bundle?.qr),[bundle]),funnel=useMemo(()=>arrayFrom(bundle?.funnel),[bundle]);
 async function reload(){setRefreshing(true);try{await Promise.all([load(),rw()]);}catch(c){setError(c instanceof Error?c.message:String(c));}finally{setRefreshing(false)}}
 async function run(key:string,fn:()=>Promise<unknown>){setBusy(key);setError(null);try{await fn();setEditing(null);setDraft(blank);await reload();}catch(c){setError(c instanceof Error?c.message:String(c));}finally{setBusy(null)}}
 function edit(kind:'campaign'|'contest'|'event'|'promotion',item:EngagementRecord){if(!advanced)return;setEditing({kind,item});setDraft({name:titleOf(item,''),description:String(item.description??''),goal:String(item.goal??''),discount:String(item.discount??''),date:String(item.event_date??'').slice(0,10),time:String(item.event_time??'').slice(0,5)});}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator/></View>;
 if(!workspace)return <View style={{padding:20}}><Text>Business workspace required.</Text></View>;
 const businessId=workspace.business_id;
 async function saveEdit(){if(!editing||!advanced)return;const id=idOf(editing.item);if(editing.kind==='campaign')return run(`edit:${id}`,()=>manageCampaign(businessId,id,'update',{name:draft.name,campaignType:String(editing.item.campaign_type??'engagement'),goal:draft.goal,status:String(editing.item.status??'draft')}));if(editing.kind==='contest')return run(`edit:${id}`,()=>manageContest(businessId,id,'update',{name:draft.name,description:draft.description}));if(editing.kind==='event')return run(`edit:${id}`,()=>manageEvent(businessId,id,'update',{title:draft.name,description:draft.description,event_date:draft.date||null,event_time:draft.time||null,location_id:editing.item.location_id??locationId}));return run(`edit:${id}`,()=>managePromotion(businessId,id,'update',{title:draft.name,description:draft.description,discount:draft.discount,location_id:editing.item.location_id??locationId}));}
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={{padding:16,gap:18,paddingBottom:56}}>
  {error?<Text style={{color:'#922'}}>{error}</Text>:null}
  <View style={hero}><Text style={{color:'#c8ead7',fontWeight:'800'}}>{advanced?'GROWTH ENGAGEMENT':'STANDARD QR ENGAGEMENT'}</Text><Text style={{color:'white',fontSize:22,fontWeight:'800'}}>{advanced?'Lifecycle + attribution + Production outcomes':'QR lifecycle + check-ins + attribution'}</Text><Text style={{color:'#dce9e2'}}>{advanced?'Growth/Enterprise unlock promotions, campaigns, contests and events.':'Standard keeps core QR engagement while advanced marketing remains locked to Growth or Enterprise.'}</Text></View>
  {!advanced?<View style={card}><Text style={heading}>Upgrade boundary</Text><Text style={{color:'#66766e'}}>Promotions, campaigns, contests and events require Business Growth or Enterprise. QR lifecycle remains available on Standard.</Text></View>:null}
  {advanced&&editing?<View style={card}><Text style={heading}>Edit {editing.kind}</Text><TextInput value={draft.name} onChangeText={v=>setDraft(s=>({...s,name:v}))} placeholder="Name / title" style={input}/><TextInput value={draft.description} onChangeText={v=>setDraft(s=>({...s,description:v}))} placeholder="Description" multiline style={[input,{minHeight:70}]}/>{editing.kind==='campaign'?<TextInput value={draft.goal} onChangeText={v=>setDraft(s=>({...s,goal:v}))} placeholder="Goal" style={input}/>:null}{editing.kind==='promotion'?<TextInput value={draft.discount} onChangeText={v=>setDraft(s=>({...s,discount:v}))} placeholder="Discount" style={input}/>:null}{editing.kind==='event'?<View style={row}><TextInput value={draft.date} onChangeText={v=>setDraft(s=>({...s,date:v}))} placeholder="YYYY-MM-DD" style={[input,{flex:1}]}/><TextInput value={draft.time} onChangeText={v=>setDraft(s=>({...s,time:v}))} placeholder="HH:MM" style={[input,{flex:1}]}/></View>:null}<View style={row}><Action label={busy?.startsWith('edit:')?'Saving…':'Save changes'} disabled={Boolean(busy)} onPress={saveEdit}/><Action label="Cancel" onPress={()=>{setEditing(null);setDraft(blank)}}/></View></View>:null}
  {advanced?<Section title="Engagement funnel">{funnel.length?funnel.map((r,i)=><View key={String(r.activity_type??i)} style={card}><Text style={{fontWeight:'800'}}>{String(r.activity_type??'engagement')} · {String(r.source??'network')}</Text><Text>{String(r.events??0)} events · {String(r.unique_users??0)} users</Text></View>):<Text>No attributed activity in this window.</Text>}</Section>:null}
  {advanced?<><Section title="Campaigns"><Action label="Create campaign" onPress={()=>run('campaign:create',()=>manageCampaign(businessId,null,'create',{name:'New Kleenest campaign',campaignType:'engagement',status:'draft'}))}/>{campaigns.map((x,i)=>{const id=idOf(x),status=String(x.status??'draft');return <Lifecycle key={id||i} title={titleOf(x,'Campaign')} detail={status} onEdit={()=>edit('campaign',x)} actions={<><Action label={status==='active'?'Pause':'Activate'} onPress={()=>run(`campaign:${id}`,()=>manageCampaign(businessId,id,status==='active'?'pause':'activate'))}/><Action label="Delete" onPress={()=>run(`campaign:delete:${id}`,()=>manageCampaign(businessId,id,'delete'))}/></>}/>})}</Section><Section title="Promotions"><Action label="Create promotion" disabled={!locationId} onPress={()=>run('promotion:create',()=>managePromotion(businessId,null,'create',{title:'New Kleenest promotion',location_id:locationId,active:true}))}/>{promotions.map((x,i)=>{const id=idOf(x),active=x.active!==false;return <Lifecycle key={id||i} title={titleOf(x,'Promotion')} detail={`${active?'Active':'Inactive'}${x.discount?` · ${String(x.discount)}`:''}`} onEdit={()=>edit('promotion',x)} actions={<Action label={active?'Deactivate':'Reactivate'} onPress={()=>run(`promotion:${id}`,()=>setPromotionActive(businessId,id,!active))}/>}/>})}</Section><Section title="Contests"><Action label="Create contest" onPress={()=>run('contest:create',()=>manageContest(businessId,null,'create',{name:'Kleenest community contest',description:'',scoring_rules:{},rewards:{}}))}/>{contests.map((x,i)=>{const id=idOf(x),status=String(x.status??'draft');return <Lifecycle key={id||i} title={titleOf(x,'Contest')} detail={status} onEdit={()=>edit('contest',x)} actions={<><Action label={status==='active'?'Pause':'Activate'} onPress={()=>run(`contest:${id}`,()=>manageContest(businessId,id,status==='active'?'pause':'activate'))}/><Action label="Delete" onPress={()=>run(`contest:delete:${id}`,()=>manageContest(businessId,id,'delete'))}/></>}/>})}</Section><Section title="Events"><Action label="Create event" disabled={!locationId} onPress={()=>run('event:create',()=>manageEvent(businessId,null,'create',{title:'New Kleenest event',location_id:locationId}))}/>{events.map((x,i)=>{const id=idOf(x);return <Lifecycle key={id||i} title={titleOf(x,'Event')} detail={[x.event_date,x.event_time].filter(Boolean).join(' · ')||'Schedule not set'} onEdit={()=>edit('event',x)} actions={<Action label="Delete" onPress={()=>run(`event:delete:${id}`,()=>manageEvent(businessId,id,'delete'))}/>}/>})}</Section></>:null}
  <Section title="QR lifecycle"><Action label="Create location QR" disabled={!locationId} onPress={()=>run('qr:create',()=>manageQr(businessId,locationId,null,'create',{label:'Kleenest location QR',customization:{}}))}/>{qrs.map((x,i)=>{const id=idOf(x),active=x.active!==false;return <View key={id||i} style={card}><Text style={{fontWeight:'800',fontSize:16}}>{titleOf(x,'Location QR')}</Text><Text>{active?'Active':'Inactive'} · {programCounts[id]??0} engagement programs</Text><View style={row}><Action label={active?'Deactivate':'Reactivate'} onPress={()=>run(`qr:${id}`,()=>setQrActive(businessId,id,!active))}/><Action label="Apply Kleenest style" onPress={()=>run(`qr:style:${id}`,()=>setQrCustomization(businessId,id,{brand:'kleenest',theme:'trust-network'}))}/><Action label="Add check-in program" onPress={()=>run(`qr:program:${id}`,()=>createQrEngagementProgram(id,{programType:'checkin',name:'Kleenest check-in',triggerCount:1}))}/></View></View>})}</Section>
 </ScrollView>;
}
const hero={backgroundColor:'#173f2d' as const,borderRadius:20,padding:18,gap:8},card={backgroundColor:'white' as const,borderRadius:16,padding:14,gap:8},heading={fontSize:20,fontWeight:'800' as const},input={borderWidth:1,borderColor:'#dce4df',borderRadius:12,padding:11},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8};
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={{gap:10}}><Text style={heading}>{title}</Text>{children}</View>}
function Action({label,onPress,disabled}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={{alignSelf:'flex-start',backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:8,borderRadius:999,opacity:disabled?0.5:1}}><Text style={{color:'white',fontWeight:'800'}}>{label}</Text></Pressable>}
function Lifecycle({title,detail,onEdit,actions}:{title:string;detail:string;onEdit:()=>void;actions:React.ReactNode}){return <View style={card}><Text style={{fontSize:16,fontWeight:'800'}}>{title}</Text><Text style={{color:'#66766e'}}>{detail}</Text><View style={row}><Action label="Edit" onPress={onEdit}/>{actions}</View></View>}
