import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { DataSummary } from '@/components/DataSummary';
import { activatePartnerAllocation,createPartnerAllocation,getPartnerAllocationRoi,getPartnerCampaignRoi,getPartnerNetworkBenchmark,listEnterpriseNetworkCampaigns,listEnterpriseNetworkMembers,listEnterprisePartnerBusinesses,listOwnedEnterpriseNetworks,recordEnterpriseCampaignOutcome } from '@/services/enterprise';
import { useBusinessWorkspace } from '@/state/businessWorkspace';

type Row=Record<string,unknown>;
const idOf=(r:Row)=>String(r.id??r.membership_id??'');
const nameOf=(r:Row,f='Item')=>String(r.name??r.business_name??r.title??f);
const businessIdOf=(r:Row)=>String(r.partner_business_id??r.business_id??r.id??'');

export default function EnterpriseEconomy(){
 const{workspace,access}=useBusinessWorkspace();
 const[networks,setNetworks]=useState<Row[]>([]),[partners,setPartners]=useState<Row[]>([]),[members,setMembers]=useState<Record<string,Row[]>>({}),[campaigns,setCampaigns]=useState<Record<string,Row[]>>({}),[insights,setInsights]=useState<Record<string,unknown>>({});
 const[selectedPartner,setSelectedPartner]=useState<Record<string,string>>({}),[selectedCampaign,setSelectedCampaign]=useState<Record<string,string>>({}),[budget,setBudget]=useState('10000'),[quantity,setQuantity]=useState('1'),[outcome,setOutcome]=useState('1'),[allocationIds,setAllocationIds]=useState<Record<string,string>>({});
 const[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!workspace)throw new Error('Business workspace required.');if(!access?.enterprise_enabled)throw new Error('Enterprise entitlement required.');const[n,p]=await Promise.all([listOwnedEnterpriseNetworks(workspace.business_id),listEnterprisePartnerBusinesses(workspace.business_id)]);const detail=await Promise.all(n.map(async network=>{const id=idOf(network);const[m,c,b,a]=await Promise.all([listEnterpriseNetworkMembers(id),listEnterpriseNetworkCampaigns(id),getPartnerNetworkBenchmark(id,30),getPartnerAllocationRoi(id,30)]);return{id,m,c,b,a};}));setNetworks(n);setPartners(p);setMembers(Object.fromEntries(detail.map(x=>[x.id,x.m])));setCampaigns(Object.fromEntries(detail.map(x=>[x.id,x.c])));setInsights(Object.fromEntries(detail.flatMap(x=>[[`benchmark:${x.id}`,x.b],[`allocation:${x.id}`,x.a]])));},[workspace,access?.enterprise_enabled]);
 useEffect(()=>{load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false));},[load]);
 async function refresh(){setRefreshing(true);setError(null);try{await load();}catch(c){setError(c instanceof Error?c.message:String(c));}finally{setRefreshing(false)}}
 async function run(key:string,fn:()=>Promise<unknown>){setBusy(key);setError(null);try{const value=await fn();if(value&&typeof value==='object'){const row=value as Row;const id=String(row.id??row.allocation_id??'');if(id&&key.startsWith('allocation:create:'))setAllocationIds(current=>({...current,[key.slice('allocation:create:'.length)]:id}));}await refresh();}catch(c){setError(c instanceof Error?c.message:String(c));}finally{setBusy(null)}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 if(!workspace||!access?.enterprise_enabled)return <View style={{padding:24}}><Text>Enterprise entitlement required.</Text></View>;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:70}}>
  {error?<View style={warn}><Text selectable style={{color:'#922'}}>{error}</Text></View>:null}
  <View style={hero}><Text style={eyebrow}>ENTERPRISE ECONOMY</Text><Text style={heroTitle}>Partner allocation, benchmark & outcome authority</Text><Text style={heroText}>Allocate budget and service units to partner businesses, activate allocations, record campaign outcomes and compare network performance using canonical Supabase Enterprise functions.</Text></View>
  {networks.map((network,index)=>{const networkId=idOf(network);const networkMembers=members[networkId]??[];const networkCampaigns=campaigns[networkId]??[];const eligible=networkMembers.length?networkMembers:partners;const partnerId=selectedPartner[networkId]??businessIdOf(eligible[0]??{});const campaignId=selectedCampaign[networkId]??idOf(networkCampaigns[0]??{});const allocationId=allocationIds[networkId]??'';return <View key={networkId||String(index)} style={card}>
   <Text style={heading}>{nameOf(network,'Enterprise network')}</Text>
   <Text style={muted}>{eligible.length} partner candidates · {networkCampaigns.length} campaigns</Text>
   <Text style={subheading}>Choose partner</Text><View style={row}>{eligible.slice(0,20).map((p,i)=>{const id=businessIdOf(p);const selected=id===partnerId;return <Pressable key={id||String(i)} onPress={()=>setSelectedPartner(current=>({...current,[networkId]:id}))} style={[chip,{backgroundColor:selected?'#173f2d':'#edf3ef'}]}><Text style={{fontWeight:'900',color:selected?'white':'#244d39'}}>{nameOf(p,'Partner')}</Text></Pressable>})}</View>
   <Text style={subheading}>Choose campaign</Text><View style={row}>{networkCampaigns.map((c,i)=>{const id=idOf(c);const selected=id===campaignId;return <Pressable key={id||String(i)} onPress={()=>setSelectedCampaign(current=>({...current,[networkId]:id}))} style={[chip,{backgroundColor:selected?'#173f2d':'#edf3ef'}]}><Text style={{fontWeight:'900',color:selected?'white':'#244d39'}}>{nameOf(c,'Campaign')}</Text></Pressable>})}</View>
   <Text style={subheading}>Create allocation</Text><View style={row}><TextInput value={quantity} onChangeText={setQuantity} keyboardType="numeric" placeholder="Quantity" style={[input,{minWidth:100}]}/><TextInput value={budget} onChangeText={setBudget} keyboardType="numeric" placeholder="Budget cents" style={[input,{minWidth:130}]}/></View><Action disabled={!partnerId} label={busy===`allocation:create:${networkId}`?'Allocating…':'Create partner allocation'} onPress={()=>run(`allocation:create:${networkId}`,()=>createPartnerAllocation(networkId,partnerId,campaignId||null,{type:'enterprise_service',quantity:Math.max(1,Number(quantity)||1),budgetCents:Math.max(0,Number(budget)||0),rationale:'Allocated from Kleenest Business Enterprise economy'}))}/>
   {allocationId?<Action secondary label="Activate newest allocation" onPress={()=>run(`allocation:activate:${networkId}`,()=>activatePartnerAllocation(allocationId))}/>:null}
   {campaignId&&partnerId?<><Text style={subheading}>Record campaign outcome</Text><TextInput value={outcome} onChangeText={setOutcome} keyboardType="numeric" style={input}/><Action label="Record attributed result" onPress={()=>run(`outcome:${networkId}`,()=>recordEnterpriseCampaignOutcome(campaignId,partnerId,{visits:Number(outcome)||0,checkIns:Number(outcome)||0,reviews:Number(outcome)||0,attributedUsers:Number(outcome)||0,pointsAwarded:Number(outcome)||0}))}/><Action secondary label="Load campaign ROI" onPress={async()=>{try{const value=await getPartnerCampaignRoi(campaignId,30);setInsights(current=>({...current,[`campaign:${campaignId}`]:value}));}catch(c){setError(c instanceof Error?c.message:String(c));}}}/>{insights[`campaign:${campaignId}`]?<DataSummary value={insights[`campaign:${campaignId}`]}/>:null}</>:null}
   <Text style={subheading}>Network benchmark</Text><DataSummary value={insights[`benchmark:${networkId}`]??{}}/><Text style={subheading}>Allocation ROI</Text><DataSummary value={insights[`allocation:${networkId}`]??{}}/>
  </View>})}
  {!networks.length?<View style={card}><Text style={muted}>Create an Enterprise partner network first. This workspace will immediately expose its partner allocation and benchmark authority.</Text></View>:null}
 </ScrollView>;
}
function Action({label,onPress,disabled,secondary}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;secondary?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={{alignSelf:'flex-start',borderRadius:999,paddingHorizontal:12,paddingVertical:8,backgroundColor:secondary?'#edf3ef':'#173f2d',opacity:disabled?.5:1}}><Text style={{fontWeight:'900',color:secondary?'#244d39':'white'}}>{label}</Text></Pressable>}
const hero={backgroundColor:'#132b21' as const,borderRadius:20,padding:18,gap:7},eyebrow={color:'#bde4cf',fontWeight:'900' as const,letterSpacing:1},heroTitle={color:'white',fontSize:24,fontWeight:'900' as const},heroText={color:'#dce8e1',lineHeight:20 as const},card={backgroundColor:'white' as const,borderRadius:16,padding:14,gap:9},warn={backgroundColor:'#fff6df' as const,borderRadius:16,padding:13},heading={fontSize:18,fontWeight:'900' as const},subheading={fontWeight:'900' as const,marginTop:4},muted={color:'#66766e',lineHeight:19 as const},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},chip={borderRadius:999,paddingHorizontal:10,paddingVertical:8},input={borderWidth:1,borderColor:'#dce4df',borderRadius:12,padding:10,flexGrow:1};
