import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,View } from 'react-native';
import { listBusinessLocations } from '@/services/business';
import { buildGovernanceReport,createEnterpriseNetwork,createWeeklyBusinessReportSchedule,getEnterpriseControlPlaneSnapshot,getLocationTrustConflicts,getLocationTrustQuality,listEnterpriseNetworkMembers,listEnterpriseNetworks,listReportingRuns,listReportingSchedules,setReportingScheduleEnabled } from '@/services/governance';
import { useBusinessWorkspace } from '@/state/businessWorkspace';

type Row=Record<string,unknown>;
function idOf(row:Row){return String(row.id??'');}
function label(row:Row,fallback:string){return String(row.name??row.title??fallback);}
function count(value:unknown){if(Array.isArray(value))return value.length;if(value&&typeof value==='object')return Object.keys(value as Row).length;return 0;}

export default function GovernanceScreen(){
 const {workspace,access}=useBusinessWorkspace();
 const [schedules,setSchedules]=useState<Row[]>([]);const [runs,setRuns]=useState<Row[]>([]);const [networks,setNetworks]=useState<Row[]>([]);
 const [snapshot,setSnapshot]=useState<Row|null>(null);const [trust,setTrust]=useState<Row|null>(null);const [conflicts,setConflicts]=useState<Row|null>(null);const [report,setReport]=useState<Row|null>(null);
 const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
 const enterprise=Boolean(access?.enterprise_enabled);
 const load=useCallback(async()=>{if(!workspace)return;const businessId=workspace.business_id;const [nextSchedules,locations,nextNetworks]=await Promise.all([listReportingSchedules(businessId),listBusinessLocations(businessId),enterprise?listEnterpriseNetworks(businessId):Promise.resolve([])]);setSchedules(nextSchedules as Row[]);setNetworks(nextNetworks as Row[]);setRuns(await listReportingRuns((nextSchedules as Row[]).map(idOf).filter(Boolean)) as Row[]);if(enterprise)setSnapshot(await getEnterpriseControlPlaneSnapshot(businessId));const first=locations[0]?.id;if(first){const [q,c]=await Promise.all([getLocationTrustQuality(first),getLocationTrustConflicts(first)]);setTrust(q);setConflicts(c);}},[workspace,enterprise]);
 useEffect(()=>{setLoading(true);load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false));},[load]);
 async function reload(){setRefreshing(true);setError(null);try{await load();}catch(c){setError(c instanceof Error?c.message:String(c));}finally{setRefreshing(false);}}
 async function run(key:string,fn:()=>Promise<unknown>){setBusy(key);setError(null);try{await fn();await reload();}catch(c){setError(c instanceof Error?c.message:String(c));}finally{setBusy(null);}}
 async function build(){if(!workspace)return;setError(null);try{setReport(await buildGovernanceReport(workspace.business_id));}catch(c){setError(c instanceof Error?c.message:String(c));}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator/></View>;
 if(!workspace)return <View style={{padding:20}}><Text>Business workspace required.</Text></View>;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:56}}>
  {error?<Text style={{color:'#9b2c2c'}}>{error}</Text>:null}
  <View style={{backgroundColor:'#173f2d',borderRadius:20,padding:18,gap:7}}><Text style={{color:'#c8ead7',fontSize:12,fontWeight:'800'}}>GOVERNANCE + TRUST</Text><Text style={{color:'white',fontSize:22,fontWeight:'800'}}>Reporting, provenance and Enterprise controls</Text><Text style={{color:'#dce9e2',lineHeight:20}}>Uses the shared reporting, trust and Enterprise authority already present in Supabase.</Text></View>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}><Metric label="Schedules" value={schedules.length}/><Metric label="Runs" value={runs.length}/><Metric label="Trust fields" value={count(trust)}/><Metric label="Conflicts" value={count(conflicts)}/>{enterprise?<Metric label="Networks" value={networks.length}/>:null}</View>
  <Section title="Reporting schedules"><Action label="Create weekly report" busy={busy==='schedule-create'} onPress={()=>run('schedule-create',()=>createWeeklyBusinessReportSchedule(workspace.business_id))}/>{schedules.map((row,i)=>{const id=idOf(row);const enabled=Boolean(row.enabled);return <Card key={id||i} title={label(row,'Business report')} detail={`${String(row.cadence??'scheduled')} · ${enabled?'enabled':'disabled'}`} action={enabled?'Disable':'Enable'} disabled={!id||busy===`schedule-${id}`} onPress={()=>run(`schedule-${id}`,()=>setReportingScheduleEnabled(id,!enabled))}/>})}</Section>
  <Section title="Trust & provenance"><JsonCard title="Location trust quality" value={trust}/><JsonCard title="Trust conflicts" value={conflicts}/><Action label="Build governance report" onPress={build}/>{report?<JsonCard title="30-day governance report" value={report}/>:null}</Section>
  {enterprise?<Section title="Enterprise control plane"><JsonCard title="Enterprise snapshot" value={snapshot}/><Action label="Create partner network" busy={busy==='network-create'} onPress={()=>run('network-create',()=>createEnterpriseNetwork('Kleenest Partner Network'))}/>{networks.map((row,i)=>{const id=idOf(row);return <NetworkCard key={id||i} row={row}/>})}</Section>:<View style={{backgroundColor:'white',borderRadius:16,padding:14,gap:4}}><Text style={{fontWeight:'800',fontSize:17}}>Enterprise controls</Text><Text style={{color:'#637269'}}>Partner networks and cross-product Enterprise controls appear only when the Enterprise entitlement is active.</Text></View>}
 </ScrollView>;
}

function NetworkCard({row}:{row:Row}){const [members,setMembers]=useState<Row[]|null>(null);const id=idOf(row);async function loadMembers(){if(!id)return;setMembers(await listEnterpriseNetworkMembers(id) as Row[]);}return <View style={{backgroundColor:'white',borderRadius:16,padding:14,gap:7}}><Text style={{fontWeight:'800',fontSize:16}}>{label(row,'Partner network')}</Text><Text style={{color:'#65746c'}}>{String(row.enabled===false?'Disabled':'Enabled')}</Text><Pressable onPress={loadMembers} style={{alignSelf:'flex-start',backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:12,paddingVertical:8}}><Text style={{fontWeight:'800',color:'#244d39'}}>Load members</Text></Pressable>{members?<Text selectable style={{color:'#5f6f66'}}>{JSON.stringify(members,null,2)}</Text>:null}</View>}
function Metric({label,value}:{label:string;value:number}){return <View style={{backgroundColor:'white',borderRadius:16,padding:14,minWidth:110,flexGrow:1}}><Text style={{color:'#66766e',fontSize:12,fontWeight:'700'}}>{label}</Text><Text style={{fontSize:24,fontWeight:'800'}}>{value}</Text></View>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={{gap:10}}><Text style={{fontSize:21,fontWeight:'800'}}>{title}</Text>{children}</View>}
function Action({label,onPress,busy}:{label:string;onPress:()=>void;busy?:boolean}){return <Pressable disabled={busy} onPress={onPress} style={{alignSelf:'flex-start',backgroundColor:'#173f2d',paddingHorizontal:14,paddingVertical:9,borderRadius:999,opacity:busy?0.5:1}}><Text style={{color:'white',fontWeight:'800'}}>{busy?'Working…':label}</Text></Pressable>}
function Card({title,detail,action,onPress,disabled}:{title:string;detail:string;action:string;onPress:()=>void;disabled?:boolean}){return <View style={{backgroundColor:'white',borderRadius:16,padding:14,gap:7}}><Text style={{fontWeight:'800',fontSize:16}}>{title}</Text><Text style={{color:'#65746c'}}>{detail}</Text><Pressable disabled={disabled} onPress={onPress} style={{alignSelf:'flex-start',backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:12,paddingVertical:8,opacity:disabled?0.5:1}}><Text style={{fontWeight:'800',color:'#244d39'}}>{action}</Text></Pressable></View>}
function JsonCard({title,value}:{title:string;value:unknown}){return <View style={{backgroundColor:'white',borderRadius:16,padding:14,gap:5}}><Text style={{fontWeight:'800',fontSize:16}}>{title}</Text><Text selectable style={{color:'#5f6f66',lineHeight:19}}>{JSON.stringify(value??{},null,2)}</Text></View>}
