import { Link } from 'expo-router';
import { ActivityIndicator,Linking,Pressable,RefreshControl,ScrollView,Text,View } from 'react-native';
import { useBusinessWorkspace } from '@/state/businessWorkspace';
import { getBusinessTierCapabilities,tierLabel } from '@/domain/businessTiers';

type BusinessRoute='/auth'|'/assistant'|'/profile'|'/members'|'/locations'|'/reviews'|'/qr-studio'|'/engagement'|'/progression'|'/prevention'|'/trust-operations'|'/notifications'|'/intelligence'|'/capabilities'|'/governance'|'/enterprise-location'|'/enterprise'|'/enterprise-economy';
function readNumber(source:Record<string,unknown>|null,key:string,fallback=0){const value=source?.[key];return typeof value==='number'&&Number.isFinite(value)?value:fallback}

export default function BusinessHome(){
 const{loading,refreshing,error,workspace,workspaces,access,entitlement,dashboard,refresh,selectWorkspace}=useBusinessWorkspace();
 if(loading)return <View style={{flex:1,alignItems:'center',justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 if(error||!workspace||!access)return <View style={{flex:1,padding:24,justifyContent:'center',gap:14}}><Text style={title}>Business access required</Text><Text style={muted}>{error??'No authorized Business workspace was resolved.'}</Text><View style={row}><Link href="/auth" replace asChild><Action label="Sign in"/></Link><Pressable onPress={refresh} style={secondary}><Text style={secondaryText}>Retry</Text></Pressable></View></View>;
 const caps=getBusinessTierCapabilities(access,entitlement),plan=tierLabel(access,entitlement);
 const metrics=[['Locations',access.location_count],['Reviews',readNumber(dashboard,'reviews')],['Check-ins',readNumber(dashboard,'check_ins')],['Redemptions',readNumber(dashboard,'redemptions')]] as const;
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={{padding:16,paddingBottom:72,gap:16}}>
  <View style={hero}><Text style={eyebrow}>KLEENEST BUSINESS · {plan.toUpperCase()}</Text><Text style={heroTitle}>{workspace.business_name??workspace.name??'Your business'}</Text><Text style={heroBody}>One command home for the work that matters: locations, customers, QR, people, engagement, trust operations and Enterprise.</Text></View>

  {workspaces.length>1?<View style={card}><Text style={kicker}>BUSINESS SWITCHER</Text><Text style={heading}>Choose business</Text><View style={row}>{workspaces.map(w=>{const active=w.business_id===workspace.business_id;return <Pressable key={w.business_id} disabled={active||refreshing} onPress={()=>selectWorkspace(w.business_id)} style={[chip,active&&chipActive]}><Text style={[chipText,active&&chipTextActive]}>{w.business_name??w.name??w.business_id.slice(0,8)}</Text></Pressable>})}</View></View>:null}

  <View style={metricsGrid}>{metrics.map(([label,value])=><View key={label} style={metric}><Text style={muted}>{label}</Text><Text style={metricValue}>{Number(value).toLocaleString()}</Text></View>)}</View>

  {access.location_count===0?<View style={warning}><Text style={{fontSize:18,fontWeight:'900',color:'#5f4515'}}>Connect your first location</Text><Text style={{color:'#725a2b',lineHeight:20}}>Locations are the foundation for reviews, QR, trust operations, analytics, Fleet handoff and Enterprise visibility.</Text><Link href="/locations" asChild><Action label="Find or add location"/></Link></View>:null}

  <View style={card}><Text style={kicker}>RUN THE BUSINESS</Text><Text style={heading}>Your operating workspaces</Text><Text style={muted}>Each job has one home. No duplicate routes and no hunting through overlapping control-center sections.</Text><View style={workspaceGrid}>
    <WorkspaceCard href="/locations" kicker="PLACES" title="Locations" detail="Claim, add, edit and operate every canonical location."/>
    <WorkspaceCard href="/reviews" kicker="CUSTOMERS" title="Reviews & replies" detail="Customer evidence, ratings, replies and review operations."/>
    <WorkspaceCard href="/qr-studio" kicker="ON-SITE" title="QR Studio" detail="Check-ins, attributed actions, templates and QR lifecycle."/>
    <WorkspaceCard href="/members" kicker="PEOPLE" title="Team & roles" detail="Membership, permissions and business authority."/>
    <WorkspaceCard href="/engagement" kicker="GROW" title="Engagement" detail="Campaigns, promotions, events and customer activation."/>
    <WorkspaceCard href="/trust-operations" kicker="OPERATE" title="Trust operations" detail="Remediation, reverification and restroom quality work."/>
  </View></View>

  <View style={card}><Text style={kicker}>SUPPORTING TOOLS</Text><Text style={heading}>Tools around the core workflow</Text><View style={routeGrid}>
    <RouteCard href="/profile" title="Business profile" detail="Public presence and business-level settings."/>
    <RouteCard href="/notifications" title="Notifications" detail="Targeted communications without leaving Business."/>
    <RouteCard href="/progression" title="Community progression" detail="Contributor programs, XP and active objectives."/>
    <RouteCard href="/prevention" title="Preventive operations" detail="Preventive work and optional Fleet handoff."/>
    <RouteCard href="/assistant" title="Kleenest AI" detail="Grounded assistance using canonical Business context."/>
  </View></View>

  {caps.enterprise?<View style={enterpriseCard}><Text style={lightKicker}>ENTERPRISE</Text><Text style={lightHeading}>Enterprise command</Text><Text style={lightBody}>Portfolio businesses, locations, Fleet state, alerts, partner networks, campaigns, outcomes and ROI live together in one Enterprise operating workspace.</Text><Link href="/enterprise" asChild><LightAction label="Open Enterprise command →"/></Link></View>:caps.enterpriseLocationFeatures?<View style={growthCard}><Text style={lightKicker}>MULTI-LOCATION</Text><Text style={lightHeading}>Growth operations</Text><Text style={lightBody}>Your plan includes multi-location and advanced operating tools. Enterprise remains a higher authority boundary.</Text><Link href="/enterprise-location" asChild><LightAction label="Open multi-location operations →"/></Link></View>:null}

  {caps.fleet?<View style={card}><Text style={kicker}>FLEET</Text><Text style={heading}>Routing & dispatch</Text><Text style={muted}>Fleet authority is active for this business. Route planning, dispatch, live map operations and driver execution stay in the dedicated Fleet app.</Text><Pressable onPress={()=>Linking.openURL('kleenest-fleet://')} style={secondary}><Text style={secondaryText}>Open Kleenest Fleet</Text></Pressable></View>:null}

  <View style={card}><Text style={kicker}>PLATFORM TOOLS</Text><Text style={heading}>Advanced controls</Text><Text style={muted}>Less-frequent administrative tools stay together and never duplicate the primary workspaces above.</Text><View style={routeGrid}><RouteCard href="/intelligence" title="Intelligence" detail="Advanced analysis and recommended actions."/><RouteCard href="/governance" title="Governance & provenance" detail="Reporting, evidence lineage and trust quality."/><RouteCard href="/capabilities" title="Capability control plane" detail="Canonical analytics, partner programs and platform capability state."/></View></View>

  <Link href="/auth" replace asChild><Pressable style={secondary}><Text style={secondaryText}>Account session</Text></Pressable></Link>
 </ScrollView>;
}

function WorkspaceCard({href,kicker,title,detail}:{href:BusinessRoute;kicker:string;title:string;detail:string}){return <Link href={href} asChild><Pressable style={workspaceCard}><Text style={workspaceKicker}>{kicker}</Text><Text style={workspaceTitle}>{title}</Text><Text style={muted}>{detail}</Text><Text style={workspaceArrow}>Open →</Text></Pressable></Link>}
function RouteCard({href,title,detail}:{href:BusinessRoute;title:string;detail:string}){return <Link href={href} asChild><Pressable style={routeCard}><View style={{flex:1,gap:3}}><Text style={{fontSize:16,fontWeight:'900',color:'#173024'}}>{title}</Text><Text style={muted}>{detail}</Text></View><Text style={{fontSize:22,color:'#547060'}}>›</Text></Pressable></Link>}
function Action({label,onPress}:{label:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={primary}><Text style={primaryText}>{label}</Text></Pressable>}
function LightAction({label,onPress}:{label:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={lightAction}><Text style={{fontWeight:'900',color:'#173f2d'}}>{label}</Text></Pressable>}
const hero={backgroundColor:'#173f2d' as const,borderRadius:24,padding:19,gap:6},eyebrow={color:'#bfe0cd' as const,fontWeight:'900' as const,letterSpacing:1},heroTitle={fontSize:30,fontWeight:'900' as const,color:'white' as const},heroBody={color:'#dce9e2' as const,lineHeight:20},title={fontSize:26,fontWeight:'900' as const,color:'#173024' as const},card={backgroundColor:'white' as const,borderRadius:18,padding:16,gap:10},heading={fontSize:21,fontWeight:'900' as const,color:'#173024' as const},kicker={fontSize:10,fontWeight:'900' as const,letterSpacing:1.2,color:'#547060' as const},muted={color:'#66766e' as const,lineHeight:20},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},metricsGrid={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:9},metric={backgroundColor:'white' as const,borderRadius:16,padding:13,minWidth:120,flexBasis:'47%' as const,flexGrow:1},metricValue={fontSize:26,fontWeight:'900' as const,color:'#173024' as const},workspaceGrid={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:9},workspaceCard={backgroundColor:'#f5f9f6' as const,borderRadius:17,padding:14,minWidth:145,flexBasis:'47%' as const,flexGrow:1,gap:4,borderWidth:1,borderColor:'#dbe7df' as const},workspaceKicker={fontSize:9,fontWeight:'900' as const,letterSpacing:1,color:'#5c7465' as const},workspaceTitle={fontSize:18,fontWeight:'900' as const,color:'#173f2d' as const},workspaceArrow={fontSize:11,fontWeight:'900' as const,color:'#173f2d' as const,marginTop:4},routeGrid={gap:8},routeCard={backgroundColor:'#f8faf9' as const,borderRadius:15,padding:13,gap:8,borderWidth:1,borderColor:'#e0e8e3' as const,flexDirection:'row' as const,alignItems:'center' as const},warning={backgroundColor:'#fff8e8' as const,borderRadius:18,padding:15,gap:8},growthCard={backgroundColor:'#1d523a' as const,borderRadius:20,padding:16,gap:9},enterpriseCard={backgroundColor:'#102d21' as const,borderRadius:20,padding:16,gap:9},lightKicker={fontSize:10,fontWeight:'900' as const,letterSpacing:1.2,color:'#bfe0cd' as const},lightHeading={fontSize:23,fontWeight:'900' as const,color:'white' as const},lightBody={color:'#dce9e2' as const,lineHeight:20},primary={alignSelf:'flex-start' as const,paddingHorizontal:15,paddingVertical:10,borderRadius:999,backgroundColor:'#173f2d' as const},primaryText={color:'white' as const,fontWeight:'900' as const},secondary={alignSelf:'flex-start' as const,paddingHorizontal:15,paddingVertical:10,borderRadius:999,backgroundColor:'#edf3ef' as const},secondaryText={fontWeight:'900' as const,color:'#244d39' as const},lightAction={alignSelf:'flex-start' as const,paddingHorizontal:13,paddingVertical:10,borderRadius:999,backgroundColor:'#f2f7f4' as const},chip={borderRadius:999,paddingHorizontal:12,paddingVertical:9,backgroundColor:'#edf3ef' as const},chipActive={backgroundColor:'#173f2d' as const},chipText={fontWeight:'800' as const,color:'#244d39' as const},chipTextActive={color:'white' as const};