import { Link } from 'expo-router';
import { ActivityIndicator,Linking,Pressable,RefreshControl,ScrollView,Text,View } from 'react-native';
import { useBusinessWorkspace } from '@/state/businessWorkspace';
import { getBusinessTierCapabilities,tierLabel } from '@/domain/businessTiers';

type BusinessRoute='/auth'|'/assistant'|'/profile'|'/members'|'/locations'|'/reviews'|'/qr-studio'|'/engagement'|'/progression'|'/prevention'|'/trust-operations'|'/notifications'|'/intelligence'|'/capabilities'|'/governance'|'/enterprise-location'|'/enterprise'|'/enterprise-economy';
function readNumber(source:Record<string,unknown>|null,key:string,fallback=0){const value=source?.[key];return typeof value==='number'&&Number.isFinite(value)?value:fallback}

export default function BusinessHome(){
 const{loading,refreshing,error,workspace,workspaces,access,entitlement,dashboard,refresh,selectWorkspace}=useBusinessWorkspace();
 if(loading)return <View style={{flex:1,alignItems:'center',justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 if(error||!workspace||!access)return <View style={{flex:1,padding:24,justifyContent:'center',gap:14}}><Text style={title}>Business access required</Text><Text style={muted}>{error??'No authorized Business workspace was resolved.'}</Text><View style={row}><Link href="/auth" replace asChild><Action label="Sign in"/></Link><Pressable onPress={refresh} style={secondary}><Text style={secondaryText}>Retry</Text></Pressable></View></View>;
 const caps=getBusinessTierCapabilities(access,entitlement),plan=tierLabel(access,entitlement);
 const metrics=[['Locations',access.location_count],['Reviews',readNumber(dashboard,'reviews')],['Check-ins',readNumber(dashboard,'check_ins')],['Redemptions',readNumber(dashboard,'redemptions')]] as const;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={{padding:16,paddingBottom:72,gap:16}}>
  <View style={hero}><Text style={eyebrow}>KLEENEST BUSINESS · {plan.toUpperCase()}</Text><Text style={heroTitle}>{workspace.business_name??workspace.name??'Your business'}</Text><Text style={heroBody}>Run locations, reviews, QR, engagement, trust and team operations from one home instead of hunting through a control-center maze.</Text></View>

  {workspaces.length>1?<View style={card}><Text style={heading}>Choose business</Text><View style={row}>{workspaces.map(w=>{const active=w.business_id===workspace.business_id;return <Pressable key={w.business_id} disabled={active||refreshing} onPress={()=>selectWorkspace(w.business_id)} style={[chip,active&&chipActive]}><Text style={[chipText,active&&chipTextActive]}>{w.business_name??w.name??w.business_id.slice(0,8)}</Text></Pressable>})}</View></View>:null}

  <View style={metricsGrid}>{metrics.map(([label,value])=><View key={label} style={metric}><Text style={muted}>{label}</Text><Text style={metricValue}>{Number(value).toLocaleString()}</Text></View>)}</View>

  <View style={card}><Text style={kicker}>QUICK ACTIONS</Text><Text style={heading}>Quick actions</Text><Text style={muted}>The things a business should be able to reach immediately after sign-in.</Text><View style={quickGrid}><Quick href="/qr-studio" title="Open QR Studio" detail="Create check-in QR, advanced actions, templates and versions"/><Quick href="/locations" title="Manage locations" detail="Claim, add, edit and operate canonical locations"/><Quick href="/reviews" title="Reviews & replies" detail="Read customer evidence and reply"/><Quick href="/members" title="Team & roles" detail="Manage Business memberships and authority"/></View></View>

  {access.location_count===0?<View style={warning}><Text style={{fontSize:18,fontWeight:'900',color:'#5f4515'}}>Attach your first location</Text><Text style={{color:'#725a2b',lineHeight:20}}>QR, reviews, trust operations and location analytics need a canonical Kleenest location.</Text><Link href="/locations" asChild><Action label="Find or add location"/></Link></View>:null}

  <View style={card}><Text style={kicker}>STANDARD BUSINESS</Text><Text style={heading}>Core business tools</Text><View style={routeGrid}><RouteCard href="/profile" title="Business CRUD" detail="Profile and public presence"/><RouteCard href="/qr-studio" title="QR Studio" detail="Standard check-in QR works on every Business plan"/><RouteCard href="/reviews" title="Customer reviews" detail="Evidence, replies and review operations"/><RouteCard href="/notifications" title="Custom Notifications" detail="Targeted Business communications"/><RouteCard href="/progression" title="Community progression" detail="Discoveries, XP and active contributor programs"/><RouteCard href="/trust-operations" title="Trust operations" detail="Remediation and reverification"/><RouteCard href="/prevention" title="Preventive operations" detail="Preventive work with optional Fleet handoff"/><RouteCard href="/assistant" title="Kleenest AI" detail="Grounded Business assistance"/></View></View>

  <View style={caps.enterpriseLocationFeatures?growthCard:lockedCard}><Text style={caps.enterpriseLocationFeatures?lightKicker:kicker}>GROWTH WORKSPACE</Text><Text style={caps.enterpriseLocationFeatures?lightHeading:heading}>Growth workspace</Text><Text style={caps.enterpriseLocationFeatures?lightBody:muted}>Multi-location operations, advanced QR design, campaigns, reporting and intelligence.</Text>{caps.enterpriseLocationFeatures?<View style={row}><Link href="/enterprise-location" asChild><LightAction label="Enterprise Location"/></Link><Link href="/engagement" asChild><LightAction label="Campaign engagement"/></Link><Link href="/intelligence" asChild><LightAction label="Advanced Intelligence"/></Link></View>:null}</View>

  <View style={caps.enterprise?enterpriseCard:lockedCard}><Text style={caps.enterprise?lightKicker:kicker}>ENTERPRISE WORKSPACE</Text><Text style={caps.enterprise?lightHeading:heading}>Enterprise workspace</Text><Text style={caps.enterprise?lightBody:muted}>Cross-business networks, Enterprise Economy, portfolio governance and shared operational authority.</Text>{caps.enterprise?<View style={row}><Link href="/enterprise" asChild><LightAction label="Enterprise network"/></Link><Link href="/enterprise-economy" asChild><LightAction label="Enterprise Economy"/></Link></View>:null}</View>

  {caps.fleet?<View style={card}><Text style={heading}>Fleet</Text><Text style={muted}>This business has Fleet authority. Routing and dispatch stay in the dedicated Fleet workspace.</Text><Pressable onPress={()=>Linking.openURL('kleenest-fleet://')} style={secondary}><Text style={secondaryText}>Open Kleenest Fleet</Text></Pressable></View>:null}

  <View style={card}><Text style={kicker}>ADVANCED OPERATIONS</Text><View style={routeGrid}><RouteCard href="/capabilities" title="Capability Control Plane" detail="Canonical analytics and operational capabilities"/><RouteCard href="/governance" title="Governance & Trust" detail="Reporting, provenance and trust quality"/>{caps.enterprise?<RouteCard href="/enterprise-economy" title="Enterprise Economy" detail="Partner allocations, network benchmarks and ROI"/>:null}</View></View>
  <Link href="/auth" replace asChild><Pressable style={secondary}><Text style={secondaryText}>Account session</Text></Pressable></Link>
 </ScrollView>;
}

function Quick({href,title,detail}:{href:BusinessRoute;title:string;detail:string}){return <Link href={href} asChild><Pressable style={quickCard}><Text style={quickTitle}>{title}</Text><Text style={muted}>{detail}</Text></Pressable></Link>}
function RouteCard({href,title,detail}:{href:BusinessRoute;title:string;detail:string}){return <Link href={href} asChild><Pressable style={routeCard}><Text style={{fontSize:16,fontWeight:'900',color:'#173024'}}>{title}</Text><Text style={muted}>{detail}</Text></Pressable></Link>}
function Action({label,onPress}:{label:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={primary}><Text style={primaryText}>{label}</Text></Pressable>}
function LightAction({label,onPress}:{label:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={lightAction}><Text style={{fontWeight:'900',color:'#173f2d'}}>{label}</Text></Pressable>}
const hero={backgroundColor:'#173f2d' as const,borderRadius:24,padding:19,gap:6},eyebrow={color:'#bfe0cd' as const,fontWeight:'900' as const,letterSpacing:1},heroTitle={fontSize:30,fontWeight:'900' as const,color:'white' as const},heroBody={color:'#dce9e2' as const,lineHeight:20},title={fontSize:26,fontWeight:'900' as const,color:'#173024' as const},card={backgroundColor:'white' as const,borderRadius:18,padding:16,gap:10},heading={fontSize:21,fontWeight:'900' as const,color:'#173024' as const},kicker={fontSize:10,fontWeight:'900' as const,letterSpacing:1.2,color:'#547060' as const},muted={color:'#66766e' as const,lineHeight:20},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},metricsGrid={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:9},metric={backgroundColor:'white' as const,borderRadius:16,padding:13,minWidth:120,flexBasis:'47%' as const,flexGrow:1},metricValue={fontSize:26,fontWeight:'900' as const,color:'#173024' as const},quickGrid={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:9},quickCard={backgroundColor:'#edf5f0' as const,borderRadius:16,padding:14,minWidth:145,flexBasis:'47%' as const,flexGrow:1,gap:4},quickTitle={fontSize:17,fontWeight:'900' as const,color:'#173f2d' as const},routeGrid={gap:8},routeCard={backgroundColor:'#f8faf9' as const,borderRadius:15,padding:13,gap:4,borderWidth:1,borderColor:'#e0e8e3' as const},warning={backgroundColor:'#fff8e8' as const,borderRadius:18,padding:15,gap:8},growthCard={backgroundColor:'#1d523a' as const,borderRadius:20,padding:16,gap:9},enterpriseCard={backgroundColor:'#102d21' as const,borderRadius:20,padding:16,gap:9},lockedCard={backgroundColor:'#eef2ef' as const,borderRadius:18,padding:16,gap:7},lightKicker={fontSize:10,fontWeight:'900' as const,letterSpacing:1.2,color:'#bfe0cd' as const},lightHeading={fontSize:21,fontWeight:'900' as const,color:'white' as const},lightBody={color:'#dce9e2' as const,lineHeight:20},primary={alignSelf:'flex-start' as const,paddingHorizontal:15,paddingVertical:10,borderRadius:999,backgroundColor:'#173f2d' as const},primaryText={color:'white' as const,fontWeight:'900' as const},secondary={alignSelf:'flex-start' as const,paddingHorizontal:15,paddingVertical:10,borderRadius:999,backgroundColor:'#edf3ef' as const},secondaryText={fontWeight:'900' as const,color:'#244d39' as const},lightAction={alignSelf:'flex-start' as const,paddingHorizontal:13,paddingVertical:9,borderRadius:999,backgroundColor:'#f2f7f4' as const},chip={borderRadius:999,paddingHorizontal:12,paddingVertical:9,backgroundColor:'#edf3ef' as const},chipActive={backgroundColor:'#173f2d' as const},chipText={fontWeight:'800' as const,color:'#244d39' as const},chipTextActive={color:'white' as const};
