import { Link } from 'expo-router';
import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,View } from 'react-native';
import { buildBusinessReportPayload,getGrowthIntelligenceBundle,type IntelligenceSection } from '@/services/intelligence';
import { getBusinessTierCapabilities } from '@/domain/businessTiers';
import { useBusinessWorkspace } from '@/state/businessWorkspace';

function count(value:unknown){if(Array.isArray(value))return value.length;if(value&&typeof value==='object')return Object.keys(value as Record<string,unknown>).length;return value==null?0:1;}
function label(key:string){return key.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}
function scalar(value:unknown){if(value==null)return '—';if(typeof value==='number')return Number.isInteger(value)?value.toLocaleString():value.toFixed(2);if(typeof value==='boolean')return value?'Yes':'No';if(typeof value==='string')return value.length>80?`${value.slice(0,77)}…`:value;return null;}
function rows(value:unknown){if(Array.isArray(value))return value.filter(v=>v&&typeof v==='object').slice(0,5) as Record<string,unknown>[];if(value&&typeof value==='object'){const obj=value as Record<string,unknown>;for(const key of['items','rows','recommendations','locations','history','results','queue'])if(Array.isArray(obj[key]))return (obj[key] as unknown[]).filter(v=>v&&typeof v==='object').slice(0,5) as Record<string,unknown>[];}return[];}
function primary(row:Record<string,unknown>,fallback:string){for(const key of['title','name','location_name','recommendation','action','status','metric_name']){const v=scalar(row[key]);if(v&&v!=='—')return v;}return fallback;}
function detail(row:Record<string,unknown>){const parts=[] as string[];for(const [k,v] of Object.entries(row)){if(['id','business_id','location_id','title','name','location_name'].includes(k))continue;const s=scalar(v);if(s&&s!=='—'){parts.push(`${label(k)}: ${s}`);if(parts.length===3)break;}}return parts.join(' · ');}

export default function IntelligenceScreen(){
 const{workspace,access,entitlement}=useBusinessWorkspace();
 const[bundle,setBundle]=useState<Awaited<ReturnType<typeof getGrowthIntelligenceBundle>>|null>(null),[report,setReport]=useState<Record<string,unknown>|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);
 const allowed=getBusinessTierCapabilities(access,entitlement).intelligence;
 const load=useCallback(async()=>{if(!workspace||!allowed)return;setBundle(await getGrowthIntelligenceBundle(workspace.business_id));},[workspace,allowed]);
 useEffect(()=>{setLoading(true);load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false));},[load]);
 async function refresh(){setRefreshing(true);setError(null);try{await load();}catch(c){setError(c instanceof Error?c.message:String(c));}finally{setRefreshing(false)}}
 async function buildReport(){if(!workspace||!allowed)return;setError(null);try{setReport(await buildBusinessReportPayload(workspace.business_id));}catch(c){setError(c instanceof Error?c.message:String(c));}}
 if(!allowed)return <View style={{flex:1,padding:24,justifyContent:'center',gap:10}}><Text style={{fontSize:24,fontWeight:'800'}}>Growth Intelligence</Text><Text style={{color:'#607067',lineHeight:21}}>This workspace requires Business Growth or Enterprise.</Text></View>;
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator/></View>;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:56}}>
  {error?<Text selectable style={{color:'#9b2c2c'}}>{error}</Text>:null}
  <View style={hero}><Text style={{color:'#c8ead7',fontWeight:'900'}}>ADVANCED INTELLIGENCE · GROWTH+</Text><Text style={{color:'white',fontSize:24,fontWeight:'900'}}>Decide what to improve next</Text><Text style={{color:'#dce9e2',lineHeight:20}}>Canonical growth, ROI, benchmark, operations and trust signals are composed here without a parallel metrics engine.</Text><Link href="/assistant" asChild><Pressable style={lightButton}><Text style={{fontWeight:'900',color:'#173f2d'}}>Ask Kleenest AI about this business</Text></Pressable></Link></View>
  {bundle?.errors.length?<View style={{backgroundColor:'#fff7e8',borderRadius:16,padding:14,gap:4}}><Text style={{fontWeight:'900',color:'#7a4d00'}}>Some intelligence sections are temporarily unavailable</Text><Text selectable style={{color:'#775f34',lineHeight:19}}>{bundle.errors.join(' · ')}</Text></View>:null}
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}><Metric label="Growth signals" value={count(bundle?.growth.data)}/><Metric label="Assets" value={count(bundle?.assets.data)}/><Metric label="Benchmarks" value={count(bundle?.benchmarks.data)}/><Metric label="Recommendations" value={count(bundle?.recommendations.data)}/></View>
  <SummarySection title="Growth cockpit" section={bundle?.cockpit}/><SummarySection title="ROI & returns" section={bundle?.roi}/><SummarySection title="Location intelligence" section={bundle?.locations}/><SummarySection title="Recommended actions" section={bundle?.recommendations}/><SummarySection title="Reverification queue" section={bundle?.reverification}/><SummarySection title="Optimization history" section={bundle?.history}/>
  <View style={card}><Text style={heading}>Reporting</Text><Text style={muted}>Build the canonical 30-day Business reporting payload for review and scheduled reporting workflows.</Text><Pressable onPress={buildReport} style={darkButton}><Text style={{color:'white',fontWeight:'900'}}>Build 30-day report</Text></Pressable>{report?<ReportSummary value={report}/>:null}</View>
 </ScrollView>;
}
function Metric({label,value}:{label:string;value:number}){return <View style={{backgroundColor:'white',borderRadius:16,padding:14,minWidth:120,flexGrow:1}}><Text style={muted}>{label}</Text><Text style={{fontSize:25,fontWeight:'900'}}>{value}</Text></View>}
function SummarySection({title,section}:{title:string;section:IntelligenceSection|undefined}){if(!section)return null;if(section.error)return <View style={card}><Text style={heading}>{title}</Text><Text style={{color:'#9b2c2c'}}>{section.error}</Text></View>;const list=rows(section.data);const obj=section.data&&typeof section.data==='object'&&!Array.isArray(section.data)?section.data as Record<string,unknown>:null;return <View style={card}><Text style={heading}>{title}</Text>{list.length?list.map((row,i)=><View key={i} style={{borderTopWidth:i?1:0,borderTopColor:'#edf1ee',paddingTop:i?9:0,gap:2}}><Text style={{fontWeight:'900',color:'#263a30'}}>{primary(row,`${title} item ${i+1}`)}</Text>{detail(row)?<Text style={muted}>{detail(row)}</Text>:null}</View>):obj?<KeyFacts value={obj}/>:<Text style={muted}>No current data in this window.</Text>}</View>}
function KeyFacts({value}:{value:Record<string,unknown>}){const facts=Object.entries(value).flatMap(([k,v])=>{const s=scalar(v);return s?[{k,s}]:[]}).slice(0,8);return facts.length?<View style={{gap:6}}>{facts.map(x=><View key={x.k} style={{flexDirection:'row',justifyContent:'space-between',gap:10}}><Text style={muted}>{label(x.k)}</Text><Text style={{fontWeight:'800',textAlign:'right',flexShrink:1}}>{x.s}</Text></View>)}</View>:<Text style={muted}>Structured intelligence is available, with no scalar summary fields in this view.</Text>}
function ReportSummary({value}:{value:Record<string,unknown>}){return <View style={{backgroundColor:'#edf4ef',borderRadius:14,padding:12,gap:5}}><Text style={{fontWeight:'900',color:'#173f2d'}}>Report ready</Text><Text style={muted}>{Object.keys(value).length} top-level reporting sections were assembled from canonical Business data.</Text></View>}
const hero={backgroundColor:'#173f2d' as const,borderRadius:22,padding:18,gap:8},card={backgroundColor:'white' as const,borderRadius:18,padding:16,gap:9},heading={fontSize:20,fontWeight:'900' as const},muted={color:'#66766e' as const,lineHeight:20},darkButton={alignSelf:'flex-start' as const,backgroundColor:'#173f2d' as const,paddingHorizontal:14,paddingVertical:10,borderRadius:999},lightButton={alignSelf:'flex-start' as const,backgroundColor:'#f1f7f3' as const,paddingHorizontal:14,paddingVertical:10,borderRadius:999,marginTop:4};
