import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { configureLiveNetworkGeofence,disableLiveNetwork,enableLiveNetwork,ensureLiveNetworkGeofences,getLiveNetworkStatus,listLiveNetworkManifest,registerLiveNetworkPush,type ManifestRow } from '@/services/liveNetwork';
import { listLiveNetworkMotifs,subscribeLiveNetworkMotifs,type LiveNetworkMotif } from '@/services/liveNetworkMotifs';
import { useBusinessWorkspace } from '@/state/businessWorkspace';

type Status=Awaited<ReturnType<typeof getLiveNetworkStatus>>;

export default function BusinessLiveNetwork(){
 const{workspace,refresh:refreshWorkspace}=useBusinessWorkspace();
 const[status,setStatus]=useState<Status|null>(null),[manifest,setManifest]=useState<ManifestRow[]>([]),[motifs,setMotifs]=useState<LiveNetworkMotif[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[radius,setRadius]=useState<Record<string,string>>({}),[lastLiveAt,setLastLiveAt]=useState<string|null>(null);
 const businessId=workspace?.business_id??null;
 const load=useCallback(async()=>{if(!businessId)return;const[nextStatus,nextManifest,nextMotifs]=await Promise.all([getLiveNetworkStatus(),listLiveNetworkManifest(businessId),listLiveNetworkMotifs(businessId,60)]);setStatus(nextStatus);setManifest(nextManifest);setMotifs(nextMotifs);setRadius(current=>Object.fromEntries(nextManifest.map(row=>[row.geofence_id,current[row.geofence_id]??String(row.radius_meters??150)])))},[businessId]);
 useEffect(()=>{setLoading(true);load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false))},[load]);
 useEffect(()=>businessId?subscribeLiveNetworkMotifs(businessId,()=>{setLastLiveAt(new Date().toISOString());listLiveNetworkMotifs(businessId,60).then(setMotifs).catch(c=>setError(c instanceof Error?c.message:String(c)))}):undefined,[businessId]);
 async function reload(){setRefreshing(true);setError(null);try{await Promise.all([load(),refreshWorkspace()])}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setRefreshing(false)}}
 async function run(key:string,action:()=>Promise<unknown>,message?:string){setBusy(key);setError(null);setNotice(null);try{await action();if(message)setNotice(message);await reload()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setBusy(null)}}
 async function provision(){if(!businessId)return;await run('provision',()=>ensureLiveNetworkGeofences(businessId),'Live Network geofences are synchronized to canonical business locations.')}
 async function enable(){if(!businessId)return;await run('enable',async()=>{const result=await enableLiveNetwork(businessId);await registerLiveNetworkPush();return result},'Live Network is enabled on this device with geofence and push delivery.')}
 async function disable(){await run('disable',disableLiveNetwork,'Live Network background geofencing is disabled on this device.')}
 async function saveGeofence(item:ManifestRow){const value=Number(radius[item.geofence_id]??item.radius_meters);if(!Number.isFinite(value)||value<50||value>1000){setError('Geofence radius must be between 50 and 1000 meters.');return;}await run(`geo:${item.geofence_id}`,()=>configureLiveNetworkGeofence(item.geofence_id,{radiusMeters:Math.round(value),notificationEnabled:item.notification_enabled,active:true}),'Geofence radius updated.');}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 if(!workspace)return <View style={{padding:24}}><Text style={heading}>Business workspace required.</Text></View>;
 const foreground=status?.foreground==='granted',background=status?.background==='granted',active=Boolean(status?.registered);
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={{padding:16,paddingBottom:72,gap:16}}>
  <View style={hero}><Text style={eyebrow}>LIVE NETWORK</Text><Text style={heroTitle}>Geofences + realtime operating motifs</Text><Text style={heroBody}>Business Live Network now closes the loop from canonical geofence and customer signals into realtime analysis: traffic momentum, quality drift, occupancy pressure and operational patterns for this workspace.</Text></View>
  {error?<View style={errorCard}><Text style={{color:'#8f2f2f',fontWeight:'800'}}>{error}</Text></View>:null}{notice?<View style={noticeCard}><Text style={{color:'#22553a',fontWeight:'800'}}>{notice}</Text></View>:null}
  <View style={metrics}><Metric label="Device state" value={active?'Running':'Off'}/><Metric label="Geofences" value={String(manifest.length)}/><Metric label="Active motifs" value={String(motifs.filter(item=>item.severity!=='quiet').length)}/><Metric label="Realtime" value={lastLiveAt?'Updated':'Listening'}/></View>
  <View style={card}><Text style={kicker}>REALTIME ANALYSIS · LAST 60 MIN</Text><Text style={heading}>Business motifs</Text><Text style={muted}>These cards are derived from the same canonical events that drive geofencing, Fleet operations, notifications and trust intelligence. The revision stream refreshes this analysis as those signals change.</Text></View>
  <View style={{gap:10}}>{motifs.map(item=><MotifCard key={item.motif_key} item={item}/>)}</View>
  <View style={card}><Text style={kicker}>DEVICE CONTROLS</Text><Text style={heading}>Live Network permission & delivery</Text><Text style={muted}>Enabling requests foreground location first, then background location, then notification access. You can turn geofencing off here at any time.</Text><View style={row}><Action disabled={Boolean(busy)} label={busy==='enable'?'Enabling…':'Enable Live Network'} onPress={enable}/><Action secondary disabled={Boolean(busy)||!active} label={busy==='disable'?'Disabling…':'Disable on this device'} onPress={disable}/><Action secondary disabled={Boolean(busy)} label="Register push again" onPress={()=>run('push',registerLiveNetworkPush,'Push delivery is registered for Kleenest Business.')}/></View></View>
  <View style={card}><Text style={kicker}>LOCATION COVERAGE</Text><Text style={heading}>Canonical geofences</Text><Text style={muted}>Business locations with valid coordinates can be synchronized into the same geofence authority used by Fleet, notifications and progression triggers.</Text><Action disabled={Boolean(busy)} label={busy==='provision'?'Synchronizing…':'Synchronize business locations'} onPress={provision}/></View>
  <View style={{gap:10}}>{manifest.length?manifest.map(item=><View key={item.geofence_id} style={card}><Text style={{fontSize:18,fontWeight:'900',color:'#173024'}}>{item.location_name??'Business location'}</Text><Text style={muted}>{[item.address,item.city,item.state].filter(Boolean).join(', ')||'Canonical location'}</Text><View style={row}><Badge text={item.active?'ACTIVE':'OFF'}/><Badge text={item.notification_enabled?'NOTIFY':'SILENT'}/></View><Text style={field}>Radius meters</Text><TextInput value={radius[item.geofence_id]??String(item.radius_meters)} onChangeText={value=>setRadius(current=>({...current,[item.geofence_id]:value}))} keyboardType="number-pad" style={input}/><View style={row}><Action secondary disabled={Boolean(busy)} label="Save radius" onPress={()=>saveGeofence(item)}/><Action secondary disabled={Boolean(busy)} label={item.notification_enabled?'Mute geofence alerts':'Enable geofence alerts'} onPress={()=>run(`notify:${item.geofence_id}`,()=>configureLiveNetworkGeofence(item.geofence_id,{radiusMeters:item.radius_meters,notificationEnabled:!item.notification_enabled,active:true}),'Geofence notification preference updated.')}/></View></View>):<View style={card}><Text style={heading}>No geofences yet</Text><Text style={muted}>Synchronize business locations above. Locations need valid coordinates before they can participate in Live Network.</Text></View>}</View>
  <View style={card}><Text style={kicker}>PRIVACY + STORE SAFETY</Text><Text style={heading}>Scoped operational intelligence</Text><Text style={muted}>Business motifs are aggregate and workspace-scoped. Raw user identifiers and precise movement are not exposed by the motif RPC. Live Network does not require microphone or overlay permission.</Text></View>
 </ScrollView>;
}
function MotifCard({item}:{item:LiveNetworkMotif}){return <View style={card}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:10}}><View style={{flex:1,gap:3}}><Text style={{fontSize:18,fontWeight:'900',color:'#173024'}}>{item.label}</Text><Text style={muted}>{motifDetail(item)}</Text></View><Badge text={item.severity.toUpperCase()}/></View><View style={row}><Badge text={`${item.observed_count} signals`}/><Badge text={`${Math.round(item.confidence*100)}% confidence`}/>{item.last_seen_at?<Badge text={`Seen ${formatTime(item.last_seen_at)}`}/>:null}</View></View>}
function motifDetail(item:LiveNetworkMotif){const e=item.evidence??{};switch(item.motif_key){case'network_momentum':return `${num(e.routes)} route intents are contributing to this workspace's current demand pattern.`;case'geofence_flow':return `${num(e.enters)} enters · ${num(e.exits)} exits · ${num(e.dwells)} dwell observations · ${num(e.dwell_seconds_avg,0)}s avg dwell.`;case'occupancy_pressure':return `${pct(e.occupancy_ratio)} occupancy · ${num(e.queue_avg,1)} avg queue · ${num(e.wait_minutes_avg,1)} min avg wait.`;case'quality_drift':return `Cleanliness ${num(e.cleanliness_avg,1)} · safety ${num(e.safety_avg,1)} · availability ${num(e.availability_avg,1)}.`;case'fleet_pressure':return `${num(e.operational_events)} Fleet events · ${num(e.open_alerts)} open alerts in this workspace.`;case'source_health':return `${num(e.degraded)} degraded sources · ${num(e.recovered)} recovered sources.`;default:return `${item.observed_count} canonical signals contributed to this motif.`}}
function num(value:unknown,digits=0){const n=Number(value);return Number.isFinite(n)?n.toFixed(digits):'—'}function pct(value:unknown){const n=Number(value);return Number.isFinite(n)?`${Math.round(n*100)}%`:'—'}function formatTime(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?'recently':d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function Metric({label,value}:{label:string;value:string}){return <View style={metric}><Text style={muted}>{label}</Text><Text style={{fontSize:19,fontWeight:'900',color:'#173024'}}>{value}</Text></View>}
function Badge({text}:{text:string}){return <View style={{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:5}}><Text style={{fontSize:11,fontWeight:'900',color:'#244d39'}}>{text}</Text></View>}
function Action({label,onPress,disabled,secondary=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;secondary?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[action,secondary&&secondaryAction,disabled&&{opacity:.45}]}><Text style={{fontWeight:'900',color:secondary?'#244d39':'white'}}>{label}</Text></Pressable>}
const hero={backgroundColor:'#173f2d' as const,borderRadius:24,padding:19,gap:7},eyebrow={color:'#bfe0cd' as const,fontWeight:'900' as const,letterSpacing:1},heroTitle={color:'white' as const,fontSize:26,fontWeight:'900' as const},heroBody={color:'#dce9e2' as const,lineHeight:20},card={backgroundColor:'white' as const,borderRadius:18,padding:16,gap:10},heading={fontSize:20,fontWeight:'900' as const,color:'#173024' as const},kicker={fontSize:10,fontWeight:'900' as const,letterSpacing:1.2,color:'#547060' as const},muted={color:'#66766e' as const,lineHeight:19},metrics={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},metric={backgroundColor:'white' as const,borderRadius:16,padding:13,minWidth:120,flexGrow:1},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},action={backgroundColor:'#173f2d' as const,borderRadius:999,paddingHorizontal:13,paddingVertical:9,alignSelf:'flex-start' as const},secondaryAction={backgroundColor:'#edf3ef' as const},field={fontSize:12,fontWeight:'900' as const,color:'#365245' as const},input={backgroundColor:'#f8faf9' as const,borderWidth:1,borderColor:'#d8e1dc' as const,borderRadius:12,paddingHorizontal:11,paddingVertical:10},errorCard={backgroundColor:'#fae7e7' as const,borderRadius:14,padding:12},noticeCard={backgroundColor:'#e4f3ea' as const,borderRadius:14,padding:12};
