import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { changeBusinessMemberRole,inviteBusinessMember,listBusinessMembers,removeBusinessMember,transferBusinessOwnership,type BusinessMember } from '@/services/members';
import { useBusinessWorkspace } from '@/state/businessWorkspace';

const roles=['admin','manager','analyst','marketing','staff'];
export default function BusinessMembersScreen(){
 const {workspace,refresh:refreshWorkspace}=useBusinessWorkspace();const[members,setMembers]=useState<BusinessMember[]>([]);const[userId,setUserId]=useState('');const[role,setRole]=useState('staff');const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!workspace)return;setMembers(await listBusinessMembers(workspace.business_id));},[workspace]);useEffect(()=>{load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false));},[load]);
 async function reload(){setRefreshing(true);try{await Promise.all([load(),refreshWorkspace()]);}catch(c){setError(c instanceof Error?c.message:String(c));}finally{setRefreshing(false);}}
 async function run(key:string,action:()=>Promise<unknown>){setBusy(key);setError(null);try{await action();await reload();}catch(c){setError(c instanceof Error?c.message:String(c));}finally{setBusy(null);}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator/></View>;if(!workspace)return <View style={{padding:20}}><Text>Business workspace required.</Text></View>;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={{padding:16,gap:14,paddingBottom:50}}>
  {error?<Text style={{color:'#9b2c2c'}}>{error}</Text>:null}
  <View style={{backgroundColor:'#173f2d',borderRadius:20,padding:18,gap:6}}><Text style={{color:'#c8ead7',fontWeight:'800'}}>BUSINESS TEAM AUTHORITY</Text><Text style={{color:'white',fontSize:23,fontWeight:'800'}}>Members, roles & ownership</Text><Text style={{color:'#dce9e2'}}>Reads are RLS-scoped. Invite, role change, removal and ownership transfer use canonical Business RPCs.</Text></View>
  <View style={card}><Text style={title}>Add member</Text><TextInput value={userId} onChangeText={setUserId} autoCapitalize="none" placeholder="Existing Kleenest user UUID" style={input}/><View style={row}>{roles.map(r=><Toggle key={r} label={r} active={role===r} onPress={()=>setRole(r)}/>)}</View><Button label={busy==='invite'?'Working…':'Invite member'} onPress={()=>run('invite',async()=>{await inviteBusinessMember(workspace.business_id,userId.trim(),role);setUserId('');})}/></View>
  {members.map(member=><View key={member.id} style={card}><Text style={{fontSize:16,fontWeight:'800'}}>{String(member.user_id)}</Text><Text style={{color:'#66766e'}}>Role: {member.role}</Text>{member.role!=='owner'?<><View style={row}>{roles.map(r=><Toggle key={r} label={r} active={member.role===r} onPress={()=>run(`role:${member.id}:${r}`,()=>changeBusinessMemberRole(workspace.business_id,member.user_id,r))}/>)}</View><Button label="Remove member" onPress={()=>run(`remove:${member.id}`,()=>removeBusinessMember(workspace.business_id,member.user_id))}/><Button label="Transfer ownership" onPress={()=>run(`owner:${member.id}`,()=>transferBusinessOwnership(workspace.business_id,member.user_id))}/></>:<Text style={{fontWeight:'800',color:'#2f6a4e'}}>Current owner</Text>}</View>)}
 </ScrollView>;
}
const card={backgroundColor:'white' as const,borderRadius:16,padding:14,gap:9},input={borderWidth:1,borderColor:'#dce4df',borderRadius:12,padding:11},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},title={fontSize:18,fontWeight:'800' as const};function Button({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={{alignSelf:'flex-start',backgroundColor:'#173f2d',borderRadius:999,paddingHorizontal:12,paddingVertical:8}}><Text style={{color:'white',fontWeight:'800'}}>{label}</Text></Pressable>}function Toggle({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={{borderRadius:999,paddingHorizontal:11,paddingVertical:8,backgroundColor:active?'#173f2d':'#eef2ef'}}><Text style={{fontWeight:'800',color:active?'white':'#33463c'}}>{label}</Text></Pressable>}
