import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { listMyNotifications,listMySentNotificationEvents,markNotificationRead,sendBusinessNotification,type NotificationEvent,type NotificationRow } from '@/services/notifications';
import { runBusinessAi } from '@/services/ai';
import { getBusinessTierCapabilities } from '@/domain/businessTiers';
import { useBusinessWorkspace } from '@/state/businessWorkspace';
const scopes=['business','followers','nearby','user'] as const;
function errorMessage(value:unknown){if(value instanceof Error)return value.message;if(value&&typeof value==='object'){const v=value as Record<string,unknown>;for(const key of['message','details','hint','code'])if(typeof v[key]==='string'&&v[key])return String(v[key]);try{return JSON.stringify(value);}catch{return'Unexpected communications error.'}}return String(value);}
function eventSummary(event:NotificationEvent){const payload=event.payload??{};const title=typeof payload.title==='string'?payload.title:typeof payload.notification_title==='string'?payload.notification_title:event.event_type;const body=typeof payload.body==='string'?payload.body:typeof payload.notification_body==='string'?payload.notification_body:null;return{title,body};}
export default function BusinessNotifications(){
 const{workspace,access,entitlement}=useBusinessWorkspace();const caps=getBusinessTierCapabilities(access,entitlement);
 const[inbox,setInbox]=useState<NotificationRow[]>([]),[sent,setSent]=useState<NotificationEvent[]>([]),[title,setTitle]=useState(''),[body,setBody]=useState(''),[scope,setScope]=useState<(typeof scopes)[number]>('business'),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState(false),[aiBusy,setAiBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const results=await Promise.allSettled([listMyNotifications(),listMySentNotificationEvents()]);const failures:string[]=[];if(results[0].status==='fulfilled')setInbox(results[0].value);else failures.push(`Inbox: ${errorMessage(results[0].reason)}`);if(results[1].status==='fulfilled')setSent(results[1].value);else failures.push(`Sent history: ${errorMessage(results[1].reason)}`);setError(failures.length?failures.join(' · '):null);},[]);
 useEffect(()=>{load().catch(c=>setError(errorMessage(c))).finally(()=>setLoading(false));},[load]);
 async function reload(){setRefreshing(true);try{await load();}catch(c){setError(errorMessage(c));}finally{setRefreshing(false)}}
 async function draftWithAi(){if(!workspace)return;setAiBusy(true);setError(null);try{const result=await runBusinessAi('notification_copy',{business:{id:workspace.business_id,name:workspace.business_name??workspace.name},audience:scope,title,body,current_tier:caps.enterprise?'enterprise':caps.growth?'growth':'standard'},`Draft customer-facing notification copy for the ${scope} audience. Preserve any facts I supplied. ${title?`Working title: ${title}.`:''} ${body?`Working message: ${body}`:'Create a useful neutral update without inventing an offer.'}`);setBody(result.answer);}catch(c){setError(errorMessage(c));}finally{setAiBusy(false)}}
 async function send(){if(!workspace||!title.trim()||!body.trim())return;setBusy(true);setError(null);try{await sendBusinessNotification(workspace.business_id,{eventType:'business_custom',title:title.trim(),body:body.trim(),audienceScope:scope,payload:{source:'kleenest_business_app'}});setTitle('');setBody('');await reload();}catch(c){setError(errorMessage(c));}finally{setBusy(false)}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator/></View>;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:56}}>
  {error?<View style={{backgroundColor:'#fff0f0',borderRadius:12,padding:11}}><Text selectable style={{color:'#922'}}>{error}</Text></View>:null}
  <View style={hero}><Text style={{color:'#c8ead7',fontWeight:'900'}}>CUSTOM NOTIFICATIONS · STANDARD+</Text><Text style={{color:'white',fontSize:24,fontWeight:'900'}}>Compose, target and review Business communications</Text><Text style={{color:'#dce9e2',lineHeight:20}}>Messages use the shared notification event pipeline and exact audience contract. Kleenest AI can draft copy, but sending remains an explicit authorized Business mutation.</Text></View>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}><Metric label="Inbox" value={inbox.length}/><Metric label="Unread" value={inbox.filter(n=>!n.read_at).length}/><Metric label="Sent" value={sent.length}/></View>
  <View style={card}><Text style={heading}>Compose notification</Text><TextInput value={title} onChangeText={setTitle} placeholder="Title" style={input}/><TextInput value={body} onChangeText={setBody} placeholder="Message" multiline style={[input,{minHeight:110,textAlignVertical:'top'}]}/><Text style={{fontWeight:'800',color:'#31483c'}}>Audience</Text><View style={row}>{scopes.map(x=><Pressable key={x} onPress={()=>setScope(x)} style={{padding:9,borderRadius:999,backgroundColor:scope===x?'#173f2d':'#edf3ef'}}><Text style={{fontWeight:'800',color:scope===x?'white':'#244d39'}}>{x}</Text></Pressable>)}</View><Text style={muted}>Business targets the current Business audience. Followers, nearby and user use the platform's canonical audience resolver.</Text><View style={row}><Button label={aiBusy?'Drafting…':'Draft with Kleenest AI'} disabled={aiBusy||busy} onPress={draftWithAi}/><Button label={busy?'Sending…':'Send notification'} disabled={busy||aiBusy||!title.trim()||!body.trim()} onPress={send}/></View>{caps.growth?<Text style={muted}>Growth/Enterprise communication intelligence can use richer Business context; delivery still uses this same canonical event pipeline.</Text>:null}</View>
  <View style={{gap:9}}><Text style={heading}>Sent history</Text>{sent.length?sent.map(e=>{const summary=eventSummary(e);return <View key={e.id} style={card}><Text style={{fontWeight:'900',fontSize:16}}>{summary.title}</Text>{summary.body?<Text style={{lineHeight:20}}>{summary.body}</Text>:null}<Text style={muted}>{e.audience_scope} · {new Date(e.created_at).toLocaleString()}</Text><Text style={{fontSize:12,color:'#7a877f'}}>{e.event_type}</Text></View>}):<Text style={muted}>No sent notification events yet.</Text>}</View>
  <View style={{gap:9}}><Text style={heading}>My notification inbox</Text>{inbox.length?inbox.map(n=><View key={n.id} style={card}><Text style={{fontWeight:'900'}}>{n.title}</Text><Text style={{lineHeight:20}}>{n.body}</Text><Text style={muted}>{n.type} · {n.read_at?'read':'unread'}</Text><Button label={n.read_at?'Mark unread':'Mark read'} onPress={async()=>{try{await markNotificationRead(n.id,!n.read_at);await reload()}catch(c){setError(errorMessage(c))}}}/></View>):<Text style={muted}>No notifications in your inbox.</Text>}</View>
 </ScrollView>;
}
function Metric({label,value}:{label:string;value:number}){return <View style={{backgroundColor:'white',borderRadius:16,padding:14,minWidth:105,flexGrow:1}}><Text style={muted}>{label}</Text><Text style={{fontSize:25,fontWeight:'900'}}>{value}</Text></View>}
const hero={backgroundColor:'#173f2d' as const,borderRadius:22,padding:18,gap:7},card={backgroundColor:'white' as const,borderRadius:18,padding:16,gap:9},heading={fontSize:20,fontWeight:'900' as const},input={borderWidth:1,borderColor:'#dce4df',borderRadius:12,padding:11},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},muted={color:'#66766e' as const,lineHeight:20};
function Button({label,onPress,disabled}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={{alignSelf:'flex-start',backgroundColor:'#173f2d',paddingHorizontal:13,paddingVertical:9,borderRadius:999,opacity:disabled?0.45:1}}><Text style={{color:'white',fontWeight:'900'}}>{label}</Text></Pressable>}
