import { Link } from 'expo-router';
import QRCode from 'react-native-qrcode-svg';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Image,Pressable,RefreshControl,ScrollView,Text,TextInput,View } from 'react-native';
import { getBusinessProfile } from '@/services/business';
import { listQrStudioAssets,saveQrStudioTemplate,type EngagementRecord } from '@/services/engagement';
import { pickAndUploadQrBranding } from '@/services/media';
import { defaultQrDesign,normalizeQrDesign,saveQrVisualDesign,type QrDesign } from '@/services/qrStudioVisual';
import { useBusinessWorkspace } from '@/state/businessWorkspace';

const MODULES:QrDesign['design']['module_style'][]=['square','rounded','dots'];
const EYES:QrDesign['design']['eye_style'][]=['square','rounded','circle'];
const FRAMES=['none','minimal','rounded','high-visibility'];
function idOf(x:EngagementRecord){return String(x.id??'')}
function titleOf(x:EngagementRecord){return String(x.label??x.title??x.name??'Kleenest QR')}
function payloadOf(x:EngagementRecord){return String(x.public_url??x.url??x.code??idOf(x))}
function cloneDesign(value:QrDesign):QrDesign{return JSON.parse(JSON.stringify(value)) as QrDesign}
function hexRgb(hex:string){const clean=hex.replace('#','');if(!/^[0-9a-f]{6}$/i.test(clean))return null;return[0,2,4].map(i=>parseInt(clean.slice(i,i+2),16)) as[number,number,number]}
function luminance(hex:string){const rgb=hexRgb(hex);if(!rgb)return null;const converted=rgb.map(v=>{const s=v/255;return s<=.03928?s/12.92:((s+.055)/1.055)**2.4});return .2126*converted[0]+.7152*converted[1]+.0722*converted[2]}
function contrast(foreground:string,background:string){const a=luminance(foreground),b=luminance(background);if(a==null||b==null)return 0;return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)}
function patchDesign(current:QrDesign,patch:Partial<QrDesign['design']>){return{...current,design:{...current.design,...patch}}}
function patchLogo(current:QrDesign,patch:Partial<QrDesign['design']['logo']>){return patchDesign(current,{logo:{...current.design.logo,...patch}})}

export default function QrDesigner(){
 const{workspace}=useBusinessWorkspace();
 const businessId=workspace?.business_id??null;
 const[assets,setAssets]=useState<EngagementRecord[]>([]),[profile,setProfile]=useState<Record<string,unknown>|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[design,setDesign]=useState<QrDesign>(cloneDesign(defaultQrDesign)),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!businessId)return;const[nextAssets,nextProfile]=await Promise.all([listQrStudioAssets(businessId),getBusinessProfile(businessId)]);setAssets(nextAssets);setProfile(nextProfile);setSelectedId(current=>nextAssets.some(row=>idOf(row)===current)?current:idOf(nextAssets[0]??{})||null)},[businessId]);
 useEffect(()=>{setLoading(true);load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false))},[load]);
 const selected=useMemo(()=>assets.find(row=>idOf(row)===selectedId)??null,[assets,selectedId]);
 useEffect(()=>{if(selected)setDesign(normalizeQrDesign(selected.customization));},[selectedId,selected]);
 const businessLogo=typeof profile?.logo_url==='string'?profile.logo_url:'';
 const score=contrast(design.design.foreground,design.design.background);
 const logoScale=Number(design.design.logo.scale||0);
 const readiness=score>=7&&design.design.quiet_zone>=4&&logoScale<=.18?'Excellent':score>=4.5&&design.design.quiet_zone>=4&&logoScale<=.22?'Ready':'Needs attention';
 const readinessTone=readiness==='Excellent'?'#1e6a43':readiness==='Ready'?'#6a531e':'#8f2f2f';
 const logoUrl=design.design.logo.source==='business'?businessLogo:design.design.logo.url??'';
 const qrLogo=logoUrl?{uri:logoUrl}:undefined;
 const eyeRadius=design.design.eye_style==='square'?0:design.design.eye_style==='rounded'?6:18;
 async function reload(){setRefreshing(true);setError(null);try{await load()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setRefreshing(false)}}
 async function save(){if(!businessId||!selected)return;if(score<4.5){setError('Increase foreground/background contrast before saving. QR contrast must be at least 4.5:1.');return;}if(design.design.logo.scale>.22){setError('Logo size cannot exceed 22% of the QR width.');return;}setBusy(true);setError(null);setNotice(null);try{await saveQrVisualDesign({businessId,qrId:idOf(selected),locationId:typeof selected.location_id==='string'?selected.location_id:null,design,summary:'Visual design saved from Business QR Studio'});setNotice('QR appearance saved. The printed QR code identity remains unchanged.');await load()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setBusy(false)}}
 async function uploadLogo(){if(!businessId)return;setBusy(true);setError(null);try{const result=await pickAndUploadQrBranding(businessId);if(result){setDesign(current=>patchLogo(current,{source:'media',url:result.publicUrl,scale:Math.max(.12,current.design.logo.scale||0),padding:4}));setNotice('Custom logo uploaded. Save the design to attach it to this QR.')}}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setBusy(false)}}
 async function saveTemplate(){if(!businessId||!selected)return;setBusy(true);setError(null);try{await saveQrStudioTemplate(businessId,null,{name:`${titleOf(selected)} visual template`,description:'Reusable branded QR appearance',design,defaultAction:{action_type:selected.action_type??selected.purpose??'checkin',action_payload:selected.action_payload??{}}});setNotice('Visual design saved as a reusable template.')}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setBusy(false)}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 if(!workspace)return <View style={{padding:24}}><Text style={heading}>Business workspace required.</Text></View>;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={{padding:16,paddingBottom:80,gap:16}}>
  <View style={hero}><Text style={eyebrow}>VISUAL QR DESIGNER</Text><Text style={heroTitle}>Make every Kleenest QR look like your business</Text><Text style={heroBody}>Customize color, finder style, framing, CTA and logos while preserving the stable code, action behavior, attribution and version history underneath.</Text></View>
  {error?<View style={errorCard}><Text style={{color:'#8f2f2f',fontWeight:'800'}}>{error}</Text></View>:null}{notice?<View style={noticeCard}><Text style={{color:'#22553a',fontWeight:'800'}}>{notice}</Text></View>:null}
  <View style={card}><View style={spread}><View style={{flex:1,gap:3}}><Text style={kicker}>QR ASSET</Text><Text style={heading}>Choose what to design</Text></View><Link href="/qr-studio" asChild><Pressable style={secondaryAction}><Text style={secondaryText}>QR Library</Text></Pressable></Link></View>{assets.length?<View style={chips}>{assets.map(asset=>{const id=idOf(asset),active=id===selectedId;return <Chip key={id} label={titleOf(asset)} active={active} onPress={()=>setSelectedId(id)}/>})}</View>:<><Text style={muted}>Create a QR asset first, then return here to brand it.</Text><Link href="/qr-studio" asChild><Pressable style={primaryAction}><Text style={primaryText}>Open QR Library</Text></Pressable></Link></>}</View>
  {selected?<>
   <View style={[previewCard,{borderColor:readinessTone}]}><Text style={kicker}>LIVE PREVIEW</Text>{design.frame.cta?<Text style={{fontSize:20,fontWeight:'900',textAlign:'center',color:'#173024'}}>{design.frame.cta}</Text>:null}<View style={{alignItems:'center',backgroundColor:design.design.background,borderRadius:design.frame.style==='rounded'?24:10,padding:Math.max(12,design.design.quiet_zone*2),borderWidth:design.frame.style==='none'?0:2,borderColor:design.design.foreground}}><QRCode value={payloadOf(selected)} size={210} color={design.design.foreground} backgroundColor={design.design.background} quietZone={design.design.quiet_zone} ecl={qrLogo?'H':'M'} logo={qrLogo} logoSize={qrLogo?Math.max(24,Math.round(210*logoScale)):undefined} logoBackgroundColor={design.design.background} logoMargin={design.design.logo.padding} eyeRadius={eyeRadius}/></View>{design.frame.supporting_text?<Text style={{textAlign:design.frame.text_align,fontSize:14*Number(design.frame.font_scale||1),fontWeight:design.frame.font_weight==='900'?'900':'700',color:'#42564a'}}>{design.frame.supporting_text}</Text>:null}<View style={spread}><View><Text style={{fontWeight:'900',color:readinessTone}}>Scan readiness: {readiness}</Text><Text style={muted}>Contrast {score.toFixed(2)}:1 · quiet zone {design.design.quiet_zone} · logo {Math.round(logoScale*100)}%</Text></View><Text selectable style={{maxWidth:150,fontSize:10,color:'#728078'}}>{payloadOf(selected)}</Text></View></View>

   <View style={card}><Text style={kicker}>DESIGN</Text><Text style={heading}>Color & QR geometry</Text><Text style={field}>Foreground color</Text><TextInput accessibilityLabel="Foreground color" value={design.design.foreground} onChangeText={value=>setDesign(current=>patchDesign(current,{foreground:value}))} autoCapitalize="characters" placeholder="#173F2D" style={input}/><Text style={field}>Background color</Text><TextInput accessibilityLabel="Background color" value={design.design.background} onChangeText={value=>setDesign(current=>patchDesign(current,{background:value}))} autoCapitalize="characters" placeholder="#FFFFFF" style={input}/><Text style={field}>Module style</Text><View style={chips}>{MODULES.map(value=><Chip key={value} label={value} active={design.design.module_style===value} onPress={()=>setDesign(current=>patchDesign(current,{module_style:value}))}/>)}</View><Text style={muted}>Module style is stored in the canonical design contract for consistent print/web renderers. The native preview prioritizes scanner-safe geometry.</Text><Text style={field}>Finder eye style</Text><View style={chips}>{EYES.map(value=><Chip key={value} label={value} active={design.design.eye_style===value} onPress={()=>setDesign(current=>patchDesign(current,{eye_style:value}))}/>)}</View><Text style={field}>Quiet zone</Text><View style={chips}>{[4,6,8,10,12].map(value=><Chip key={value} label={`${value} modules`} active={design.design.quiet_zone===value} onPress={()=>setDesign(current=>patchDesign(current,{quiet_zone:value}))}/>)}</View></View>

   <View style={card}><Text style={kicker}>BRANDING</Text><Text style={heading}>Logo</Text><Text style={muted}>Logos use high error correction and are capped at 22% of QR width. Smaller logos produce the strongest scan margin.</Text><View style={chips}><Chip label="No logo" active={design.design.logo.source==='none'} onPress={()=>setDesign(current=>patchLogo(current,{source:'none',url:null,scale:0}))}/><Chip label="Use business logo" active={design.design.logo.source==='business'} onPress={()=>setDesign(current=>patchLogo(current,{source:'business',url:businessLogo||null,scale:.14,padding:4}))}/><Chip label="Custom logo" active={design.design.logo.source==='media'} onPress={()=>{}}/></View>{businessLogo?<View style={brandRow}><Image source={{uri:businessLogo}} style={logoThumb}/><Text style={muted}>Current Business profile logo</Text></View>:<Text style={muted}>No Business profile logo is set. You can upload a custom logo below.</Text>}<Pressable disabled={busy} onPress={uploadLogo} style={secondaryAction}><Text style={secondaryText}>{busy?'Working…':'Upload custom logo'}</Text></Pressable><Text style={field}>Logo size</Text><View style={chips}>{[0.10,0.12,0.14,0.16,0.18,0.20,0.22].map(value=><Chip key={value} label={`${Math.round(value*100)}%`} active={Math.abs(design.design.logo.scale-value)<.001} onPress={()=>setDesign(current=>patchLogo(current,{scale:value}))}/>)}</View>{logoUrl?<View style={brandRow}><Image source={{uri:logoUrl}} style={logoThumb}/><Text style={muted}>Logo preview · high QR error correction enabled</Text></View>:null}</View>

   <View style={card}><Text style={kicker}>FRAME + MESSAGE</Text><Text style={heading}>Turn the code into a sign</Text><Text style={field}>Frame style</Text><View style={chips}>{FRAMES.map(value=><Chip key={value} label={value} active={design.frame.style===value} onPress={()=>setDesign(current=>({...current,frame:{...current.frame,style:value}}))}/>)}</View><Text style={field}>CTA label</Text><TextInput value={design.frame.cta??''} onChangeText={value=>setDesign(current=>({...current,frame:{...current.frame,cta:value||null}}))} placeholder="Scan to check in" style={input}/><Text style={field}>Supporting text</Text><TextInput value={design.frame.supporting_text??''} onChangeText={value=>setDesign(current=>({...current,frame:{...current.frame,supporting_text:value||null}}))} placeholder="Earn XP and help keep restroom data fresh" style={input}/></View>

   <View style={card}><Text style={kicker}>SCAN SAFETY</Text><Text style={heading}>Scan readiness</Text><View style={{backgroundColor:`${readinessTone}18`,borderRadius:14,padding:12,gap:5}}><Text style={{fontSize:18,fontWeight:'900',color:readinessTone}}>{readiness}</Text><Text style={muted}>Contrast {score.toFixed(2)}:1. Minimum save threshold is 4.5:1. Quiet zone must be at least four modules. Logo size is constrained to 22%.</Text></View></View>
   <View style={card}><Text style={kicker}>SAVE</Text><Text style={heading}>Versioned, stable-code design</Text><Text style={muted}>Saving updates only the canonical design metadata and writes a new QR version. It does not rotate the printed code or break existing attribution.</Text><View style={chips}><Pressable disabled={busy||readiness==='Needs attention'} onPress={save} style={[primaryAction,(busy||readiness==='Needs attention')&&{opacity:.45}]}><Text style={primaryText}>{busy?'Saving…':'Save QR design'}</Text></Pressable><Pressable disabled={busy} onPress={saveTemplate} style={secondaryAction}><Text style={secondaryText}>Save as template</Text></Pressable></View></View>
  </>:null}
 </ScrollView>;
}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[chip,active&&chipActive]}><Text style={[chipText,active&&chipTextActive]}>{label}</Text></Pressable>}
const hero={backgroundColor:'#173f2d' as const,borderRadius:24,padding:19,gap:7},eyebrow={color:'#bfe0cd' as const,fontWeight:'900' as const,letterSpacing:1},heroTitle={color:'white' as const,fontSize:26,fontWeight:'900' as const},heroBody={color:'#dce9e2' as const,lineHeight:20},card={backgroundColor:'white' as const,borderRadius:18,padding:16,gap:10},previewCard={backgroundColor:'white' as const,borderRadius:22,padding:16,gap:12,borderWidth:2},heading={fontSize:20,fontWeight:'900' as const,color:'#173024' as const},kicker={fontSize:10,fontWeight:'900' as const,letterSpacing:1.2,color:'#547060' as const},muted={color:'#66766e' as const,lineHeight:19},field={fontSize:12,fontWeight:'900' as const,color:'#365245' as const},input={backgroundColor:'#f8faf9' as const,borderWidth:1,borderColor:'#d8e1dc' as const,borderRadius:12,paddingHorizontal:11,paddingVertical:10},chips={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},chip={borderRadius:999,paddingHorizontal:11,paddingVertical:8,backgroundColor:'#edf3ef' as const,borderWidth:1,borderColor:'#d8e1dc' as const},chipActive={backgroundColor:'#173f2d' as const,borderColor:'#173f2d' as const},chipText={fontSize:12,fontWeight:'900' as const,color:'#244d39' as const},chipTextActive={color:'white' as const},primaryAction={alignSelf:'flex-start' as const,backgroundColor:'#173f2d' as const,borderRadius:999,paddingHorizontal:14,paddingVertical:10},primaryText={fontWeight:'900' as const,color:'white' as const},secondaryAction={alignSelf:'flex-start' as const,backgroundColor:'#edf3ef' as const,borderRadius:999,paddingHorizontal:14,paddingVertical:10},secondaryText={fontWeight:'900' as const,color:'#244d39' as const},spread={flexDirection:'row' as const,justifyContent:'space-between' as const,alignItems:'center' as const,gap:10},brandRow={flexDirection:'row' as const,alignItems:'center' as const,gap:10},logoThumb={width:54,height:54,borderRadius:12,backgroundColor:'#edf3ef'},errorCard={backgroundColor:'#fae7e7' as const,borderRadius:14,padding:12},noticeCard={backgroundColor:'#e4f3ea' as const,borderRadius:14,padding:12};
